### ISSUE TITLE
Forking a project does not work for certain users in 8.9.6-1

### ISSUE THREAD

**Issue by QuickJack** [sameersbn/docker-gitlab#834] opened 2016-08-09 16:09 UTC
Forking works for users that have been created until a certain point in time. When one of the latest users created tries to fork, the process stops with "The repository could not be imported." and "The project could not be forked.". Pressing the "Start Import" button displays a page "Forking in progess" that never completes.
I checked that all tested users have exactly the same settings and rights in the project to be forked.

**Comment by patrickc91** [comment] 2016-08-09 17:08
I'm not sure if this is a great solution, but I too had this problem and I found that some of my data directories had odd permissions. Some directories were owned by `root` and others were owned by `git`. By going in and changing the owner of the directories I was able to resolve this issue.

These permissions issues were causing the inability to fork and import projects and the inability to change the Avatar image for some repositories and users.

**Comment by SolidNerd** [comment] 2016-08-09 17:21
@patrickc91  Thanks for the Hint.  In our normal case all repositories should have the correct permission, because when you start this container all directory permissions will be sanitized.

@QuickJack  If is this the case that some permissions changed I would like to know where. So i can try to reproduce it and hopefully fix the problem.

**Comment by QuickJack** [comment] 2016-08-09 17:49
@patrickc91 Do you mean the directories under /srv/docker/gitlab/gitlab/repositories ? The user that was trying to fork the repository in question did not have any personal projects. That is, there was no directory for that user. However, it was possible to create a personal project which also created  a personal folder under /srv/docker/gitlab/gitlab/repositories.

@SolidNerd I will check the permissions tomorrow and post the results.

**Comment by sameersbn** [comment] 2016-08-09 17:55
@QuickJack If you launch the container with `app:sanitize` argument it'll set the file and folder permissions to what gitlab expects. So if its indeed the cause, it should get resolved. Please try fixing the permissiong using `app:sanitize` and avoid doing a `chown`/`chmod`.

**Comment by patrickc91** [comment] 2016-08-09 18:10
@QuickJack That's exactly where I'm talking about. For some reason we were having issues with those personal project folders being created and owned by `root`, causing permission errors for the `git` user. I would highly recommend listening to @sameersbn though. If I had known about that sooner, I would have tried it out before using `chown/chmod`.

**Comment by QuickJack** [comment] 2016-08-09 19:30
Thanks for all the replies.

@sameersbn  I am using docker-compose on my production server. I also have a testing server. How exactly do you suggest me to run the app:sanitize command? According to the "Host UID / GID Mapping" section of README.md it should be done like:

docker run --name gitlab -d sameersbn/gitlab:8.9.6-1 app:sanitize

That would create a new container named gitlab which is not removed automatically. Am I missing something?

**Comment by mikew** [comment] 2016-08-09 19:41
You're correct, but [`app:sanitize` changes permissions and owners of files and folders](https://github.com/sameersbn/docker-gitlab/blob/eff3895214bdc475d2aaa0af094bf8d31641b7f1/assets/runtime/functions#L1069-L1106). Since they're bind-mounted in Docker, those changes will persist.

Maybe try one of:

```sh
# This will execute the command in an already running container
docker-compose exec gitlab /sbin/entrypoint.sh app:sanitize

# This will spawn a new container, run the command, and delete the container.
docker-compose run --rm gitlab /sbin/entrypoint.sh app:sanitize
```

**Comment by sameersbn** [comment] 2016-08-10 04:37
Thanks @mikew `docker-compose exec gitlab /sbin/entrypoint.sh app:sanitize` is indeed the easiest :smile:

**Comment by QuickJack** [comment] 2016-08-10 07:46
Thanks for the advice. I did a quick check of the permissions by logging in to the gitlab container. All directories in the repositories folder have owner & group set to git. I never did any manual changes within this folder. Following is the output of the app:sanitize command:

$ sudo docker-compose exec gitlab /sbin/entrypoint.sh app:sanitize
No such command: exec

Commands:
  build              Build or rebuild services
  config             Validate and view the compose file
  create             Create services
  down               Stop and remove containers, networks, images, and volumes
  events             Receive real time events from containers
  help               Get help on a command
  kill               Kill containers
  logs               View output from containers
  pause              Pause services
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pulls service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  unpause            Unpause services
  up                 Create and start containers
  version            Show the Docker-Compose version information

$ docker-compose --version
docker-compose version 1.6.2, build 4d72027

**Comment by QuickJack** [comment] 2016-08-10 08:10
I updated my docker-compose to 1.8.0 which includes the exec command. After running "docker-compose exec gitlab /sbin/entrypoint.sh app:sanitize", GitLab displays "Whoops, GitLab is taking too much time to respond". Hitting F5 didn't help. Obviously, it is not possible to run this command without killing the running GitLab instance. I think that is a different problem which should be analyzed.

The good news is, that after restarting the GitLab instance I am now able to fork projects by impersonating the users in question. The app:sanitize command solved the issue. However, the question remains why these permissions were wrong. I never did any manual changes within the repositories folder.

Many thanks for all the good ideas to find a quick solution for this issue.

**Comment by QuickJack** [comment] 2016-08-10 10:11
Unfortunately, it does not work on my production server. I also did "docker-compose exec gitlab /sbin/entrypoint.sh app:sanitize". But I am still unable to fork.

**Comment by patrickc91** [comment] 2016-08-10 18:25
You shouldn't have to use `docker-compose exec` to run code inside a running container.

Just a simple `docker exec gitlab /sbin/entrypoint.sh app:sanitize` does the trick for me.

**Comment by mikew** [comment] 2016-08-10 18:27
@patrickc91 With docker-compose, the generated container name could differ from machine to machine, since it's based on the parent folder name. In fact, in your example it would actually be `gitlab_gitlab_1`. Using `docker-compose exec` takes out that guesswork.

**Comment by patrickc91** [comment] 2016-08-10 18:57
@mikew That's true, and something I didn't really think about as I've gotten into the habit of naming my "constant" containers. I do a lot of development on a Windows machine though, so `docker-compose exec` doesn't allow you to see the output of your command. You're required to use `-d` and I've yet to see how I can get the output of commands run with `docker-compose exec`.

I did test the `docker-compose exec` version in my Linux environment and it works.

**Comment by sameersbn** [comment] 2016-08-11 05:56
Glad that it worked. And thanks @QuickJack for the sharing the details of your resolution.

**Comment by QuickJack** [comment] 2016-08-11 08:04
@sameersbn It is only a workaround but not a solution. Do you plan to further analyze it? I am not sure if it's a problem in docker-gitlab or the upstream GitLab itself.

**Comment by sameersbn** [comment] 2016-08-11 16:42
The cause of the issue is probably caused by the user running `chown` or moving the data directory which caused the ownerships and permissions to change.

The permanent fix this issue is to always to `app:sanitize` when the container is started. But this results in a longer startup time when you a large number of repos.

**Comment by patrickc91** [comment] 2016-08-11 17:02
> The cause of the issue is probably caused by the user running chown or moving the data directory which caused the ownerships and permissions to change.

This is exactly what I did I believe. When I first set up my Gitlab instance, I had no experience with Docker or Gitlab or anything related to my current setup. So I ended up moving things between a couple of servers without doing the proper backup/restore rake tasks, which caused some weird permissions problems.

**Comment by QuickJack** [comment] 2016-08-11 18:26
The problem still occurs after doing app:sanitize. Suppose there is a new user and all permissions are set correctly. This user does not have a personal folder. If such a user tries to fork a repository, it won't work. But if he creates a personal project, it works and a personal folder is created.

Once such a personal folder exists, it is possible to fork repositories. GitLab will never remove a personal folder. This doesn't even happen if all personal repositories and forks are deleted. In other words, once a user creates a personal project (and indirectly a personal folder), the problem is gone forever.

**Comment by sameersbn** [comment] 2016-08-12 04:31
> Suppose there is a new user and all permissions are set correctly. This user does not have a personal folder
This is not supposed to happen. I think GitLab will create a the personal folder for each user when the user is created. If it does not, then there's could be some issue. I check if this is the case.

**Comment by QuickJack** [comment] 2016-08-12 09:06
You are totally right. The permissions problems have been resolved on both my test server and my production server. If I now create a new user, GitLab will also create a personal folder for that user. This did obviously not happen when creating some users in the last weeks.

If one of the users without a personal folder tries to fork, it will fail. This is because the software assumes, that the folder already exists. It doesn't make this assumtion in case a personal project is created. In this case it simply creates the personal folder.

We can now argue, that the forking problem is some kind of secondary bug. If we didn't had the permissions problem we didn't hit the forking problem. But anyway, I think it is a problem, that the personal folder is created when creating personal projects but it's not when trying to fork a project.

**Comment by SolidNerd** [comment] 2016-08-18 10:20
I will close this issue now. I think it's resolved otherwise reopen this.

**Closed by SolidNerd** 2016-08-18 10:20 UTC
