### ISSUE TITLE
Tag 8.6.5 not found in repository sameersbn/gitlab

### ISSUE THREAD

**Issue by nathanleclaire** [sameersbn/docker-gitlab#666] opened 2016-04-14 23:42 UTC
```
Tag 8.6.5 not found in repository docker.io/sameersbn/gitlab
```

Just FYI: When attempting to `docker-compose up` on `master`, I ran into this issue.  Indeed, it's not present at https://hub.docker.com/r/sameersbn/gitlab/tags/ -- should it be `sameersbn/gitlab:8.6.4`?

cc @sameersbn

**Comment by lenovouser** [comment] 2016-04-15 00:05
Duplicate of #662

**Comment by nathanleclaire** [comment] 2016-04-15 17:45
Why have the Compose file set to an image that doesn't exist though?  Even if the project is blocked on upgrading to that version, couldn't an older one still be used?

**Comment by sameersbn** [comment] 2016-04-17 07:13
@nathanleclaire I was careless while releasing 8.6.5. The changes from `8.6.4` to `8.6.5` were insignificant enough that and I went ahead and tagged a new release before trying to build the image locally. This was a big mistake from my side.

As it stands today, I have worked around the issue and made new releases. Sorry for the inconvenience.

**Closed** 2016-04-17 07:15 UTC

**Comment by nathanleclaire** [comment] 2016-04-18 16:50
Cool no problem thanks @sameersbn
