### ISSUE TITLE
Fail at start due file permissions

### ISSUE THREAD

**Issue by patope** [sameersbn/docker-gitlab#2144] opened 2020-05-16 08:10 UTC
12.10.4 fails in error. 12.9.5 works fine
```
Loading /etc/docker-gitlab/runtime/env-defaults
Mapping UID and GID for git:git to 1006:1006
Initializing logdir...
Initializing datadir...
Installing configuration templates...
SSL Key, SSL Certificate and DHParam were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
SSL key and certificates for Registry were not found
Assuming that the Registry is running behind a HTTPS enabled load balancer.
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
Can't open /home/git/gitlab/.gitlab_shell_secret for writing, Permission denied
140680452825536:error:0200100D:system library:fopen:Permission denied:../crypto/bio/bss_file.c:72:fopen('/home/git/gitlab/.gitlab_shell_secret','w')
140680452825536:error:2006D002:BIO routines:BIO_new_file:system lib:../crypto/bio/bss_file.c:81:

```

**Comment by solidnerd** [comment] 2020-05-17 11:00
Hey @patope,

thanks for reporting this. I'll try to reproduce it and see how we can solve this ;).

**Comment by cwildfoerster** [comment] 2020-05-18 11:54
Same error here.

**Comment by fgracia** [comment] 2020-05-18 15:20
Hello,

Same error, it seems to be related to `USERMAP_UID` and `USERMAP_GID`.
If I don't use this mapping (just comment the variables in `docker-compose.yml), it works fine (but you may have to update the privileges on your local storage, that is mounted on `/home/git/data`).

**Comment by solidnerd** [comment] 2020-05-18 17:56
I think this relates to the merge of #1443

**Comment by patope** [comment] 2020-05-18 20:49
Filter condition (`! -uid ${USERMAP_ORIG_UID} -o ! -gid ${USERMAP_ORIG_GID}`) looks incorrect. It filters out all files whose owner is original uid and gid. Should do opposite and pick only files whose owner is original uid or gid.
`-uid ${USERMAP_ORIG_UID} -o -gid ${USERMAP_ORIG_GID}`

**Comment by cwildfoerster** [comment] 2020-05-19 11:23
> Hello,
> 
> Same error, it seems to be related to `USERMAP_UID` and `USERMAP_GID`.
> If I don't use this mapping (just comment the variables in `docker-compose.yml`), it works fine (but you may have to update the privileges on your local storage, that is mounted on `/home/git/data`).

Yes, i am using uid/uid mapping.

**Comment by solidnerd** [comment] 2020-05-19 17:29
Hey, I won’t have any free time today need to delay it to Thursday.

**Comment by solidnerd** [comment] 2020-05-21 20:51
Forgot this today 😅 . I'll look tomorrow into it how we can solve this back.

**Comment by solidnerd** [comment] 2020-05-24 14:55
I'll revert #1443  to solve. It will be in `13.0.0` that will be released tomorrow. I hope this helps and make the image usable again.

**Comment by cwildfoerster** [comment] 2020-05-24 15:06
Thank you, i don't mind waiting a couple of seconds for it, ssd to the rescue.

**Closed** 2020-05-25 04:56 UTC

**Comment by K0ertis** [comment] 2020-05-28 10:57
I got this error after V12.9.5, which I have backups for.
The next release is already 12.10.4 for the docker container which I cannot start up, this continues up to 13.0.0.
But running 13.0.0 I can not restore my backups from 12.9.5 due **GitLab version mismatch**
What can I do?
