### ISSUE TITLE
Error: "transfer closed with xxx bytes remaining to read" when cloning over HTTPS

### ISSUE THREAD

**Issue by lucas-clemente** [sameersbn/docker-gitlab#226] opened 2014-12-16 19:40 UTC
I'm running docker-gitlab with a pretty standard setup (see below) behind a SSL-terminating nginx (on the docker host).  Normally everything is running perfectly, cloning over ssh works like a charm. But sometimes cloning over https fails with an error message:

```
~/Desktop → git clone https://example.com/foobar/foo.git
Cloning into 'foo'...
fatal: unable to access 'https://example.com/foobar/foo.git/': transfer closed with 2737 bytes remaining to read
```

I've looked into the logs. My SSL-terminator (nginx) says `upstream prematurely closed connection while reading upstream`, so I guess it's not at fault. Next I looked into the nginx log at `/var/log/gitlab/nginx/gitlab_error.log`, and found this:

```
2014/12/15 16:26:02 [alert] 282#0: *1246 readv() failed (13: Permission denied) while reading upstream
```

I can't figure out the reason. Obviously the socket has the correct permissions, otherwise it wouldn't work at all. I also found that [improper permissions on the proxy_temp folder can cause this](http://derekneely.com/2009/06/nginx-failed-13-permission-denied-while-reading-upstream/), but the permissions on `/var/lib/nginx/proxy/` look fine.

I'd be very happy to help debug this further, but I don't know where to start. Any ideas?

docker-gitlab variables are:

      GITLAB_HOST: ...
      GITLAB_PORT: 443
      GITLAB_EMAIL: ...
      GITLAB_HTTPS: true
      GITLAB_HTTPS_HSTS: true
      GITLAB_HTTPS_HSTS_MAXAGE: 2592000
      JIRA_URL: ...
      SMTP_USER: ...
      SMTP_PASS: ...

**Comment by lucas-clemente** [comment] 2015-01-02 14:19
Thanks for your reply! I couldn't find anything on openssl / nginx and the quoted error message, do you maybe still remember where you read something about it?

Somehow I don't understand how it can be a problem with libssl though. As I wrote above, the TLS connection is terminated from nginx running *directly on the docker host*, proxying to the gitlab docker container. However, the `Permission denied` error appears on the nginx proxy running *inside the container*. But then again, I might just be misinterpreting things ;)

Happy new year!

**Comment by sameersbn** [comment] 2015-01-02 14:41
I will try to look it up and let you know.

**Comment by sameersbn** [comment] 2015-02-07 10:50
@lucas-clemente I was checking this issue today and found that the git process prematurely gives up on large repos. 

```bash
# git clone https://git.example.com/opensource/openwrt.git
Cloning into 'openwrt'...
remote: Counting objects: 290509, done.
remote: Compressing objects: 100% (79939/79939), done.
error: RPC failed; result=56, HTTP code = 200MiB | 8.62 MiB/s   
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

This happens on both http and https urls. Worth nothing is that it works sometimes. Next I tried connecting directly to the containers http port

```bash
git clone http://$(docker inspect --format {{.NetworkSettings.IPAddress}} gitlab)/opensource/openwrt.git -v
Cloning into 'openwrt'...
POST git-upload-pack (240 bytes)
remote: Counting objects: 290509, done.
remote: Compressing objects: 100% (79939/79939), done.
remote: Total 290509 (delta 198066), reused 289751 (delta 197308)
Receiving objects: 100% (290509/290509), 106.91 MiB | 20.02 MiB/s, done.
Resolving deltas: 100% (198066/198066), done.
Checking connectivity... done.
```

And had no problems cloning using the git http clone url. Maybe you can give it a shot as well. If you see this behaviour as well, then it appears that there would be some configuration required at the reverse proxy.

I found the following reports of the same issue 
- https://github.com/gitlabhq/gitlabhq/issues/6832
- https://gitlab.com/gitlab-org/gitlab-ce/issues/232

**Comment by ulrichSchreiner** [comment] 2015-02-27 06:31
hi,
i have the same problem with big repositories. i increased the unicorn timeout as well as the workers, but now the unicorn workerkiller stops everything. now i patch 

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/config.ru

to increase the memory settings. it would be great for your dockerfile to have some settings for this too.

**Comment by sameersbn** [comment] 2015-02-27 09:12
@ulrichSchreiner does increasing the memory settings on unicorn fix the issue?

**Comment by ulrichSchreiner** [comment] 2015-02-27 09:15
on serverside, yes. in nginx-log i see a successfull HTTP 200 with a 1GB of data transferred. no more errors inside of gitlab.

but now i have an issue on the client

http://ubuntu.aspcode.net/view/635400140124705175296526/error-gnutlshandshake-falied

currently i compile a git-client with openssl and try again :-)

**Comment by ulrichSchreiner** [comment] 2015-02-27 13:21
solved!

multiple problems, but
 - first patched memory setting for the unicorn worker
 - then used a modern git (ubuntu 14.04 did not work for me)
 - and next: we had the docker image behind another loadbalancer (a farm of nginx's). they do proxy-buffering with a max-tempfilesize (http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size) of 1G. and this frontend-ELB cutted of my clone. so i added `add_header X-Accel-Buffering no;` to the nginx inside your docker container

and now it works! i don't know if it would be a good idea to put this setting inside your dockerfile, but an option would not be too bad :-)

**Comment by sameersbn** [comment] 2015-02-27 13:26
@ulrichSchreiner cool. will try out your changes and make the changes as required. thanks

**Comment by ulrichSchreiner** [comment] 2015-02-27 17:50
hi,

one additional note: i did a `git clone https://...` from a WAN client to a loadbalancer with a nginx which then connected to your dockercontainer which also contains a nginx. my repo was about ~1.2GB of data and gitlab pushed out the bytes really fast to your nginx. an your nginx pushed out the bytes to our sencond nginx (our LB). but here we could not deliver the bytes as fast as we wanted (the client was connected via a slow line) and so this LB buffered, because the default is `on` (http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering). and the default for the temp-file-size is 1GB. so this all lead to my problem: after 1GB of data the stream of data ended and my client received an error.

but i think if a client connects directly to your nginx you would have the same problem, because you also use proxy_buffering and the default size for temp-file-size is also 1GB. 

-> if you have a loadbalancer in front, it would be a good option to include the `add_header X-Accel-Buffering no;` (optional). But if you do not have a LB in front, you should have the options to disable proxy-buffering and/or set the size for the `proxy_max_temp_file_size`.

**Comment by sameersbn** [comment] 2015-02-27 18:19
@ulrichSchreiner shit just got complicated :laughing:

**Comment by smoebody** [comment] 2015-03-30 21:32
hi all,
i experience this problem when using gitlab-ci as it's pulling the repo via https. can anyone please be more detailed what i have to adjust so that it works?

**Comment by sameersbn** [comment] 2015-03-31 06:51
@smoebody I was trying to reproduce this issue recently to test a probable fix. However I was not able to reproduce the issue. Can you try a fix for me.

1. Login to the running gitlab container `docker exec -it gitlab bash`
2. Edit `/etc/nginx/sites-enabled/gitlab` server block to replace

```nginx
upstream gitlab {
  server unix:/home/git/gitlab/tmp/sockets/gitlab.socket fail_timeout=0;
}
```

with

```nginx
upstream gitlab {
  server 127.0.0.1:8080 fail_timeout=0;
}
```

3. Stop the nginx server `supervisorctl stop nginx`
4. Start the nginx server `supervisorctl start nginx`
5. Try cloning via http/https clone url
6. Let me know if it fixes the issue.
7. If you are able to clone, test many more times to be absolutely sure. Because when I was seeing this issue it was hit or miss. It would work sometimes and would fail other time.

If this does not resolve the issue, revert the above changes and try the changes from PR #269. You only need to make the changes to `/etc/nginx/sites-enabled/gitlab` where you want to set the following options in the nginx configuration

```nginx
add_header X-Accel-Buffering no
proxy_buffering off
```

Refer to the PR for the appropriate place to insert these settings in the nginx configuration. Once you have these changes in place stop and start the nginx server the same way as described above, i.e. steps 3 and 4.

Let me know  the results.

**Comment by sameersbn** [comment] 2015-03-31 06:54
@smoebody fyi, `supervisorctl status` will let you know if all the daemons are running

**Comment by smoebody** [comment] 2015-04-06 11:30
@sameersbn, sorry for the delay.

i tried the your first suggestion by changing from unix-socket to tcp-socket and it seems that did the trick, although i would have preferred the  second fix to solve the problem as its more plausible to me ;)
But for now i did 5 build retries without the error occuring again.

thanks again for your help!

**Comment by sameersbn** [comment] 2015-04-06 15:10
@smoebody did you try the second fix?

**Comment by smoebody** [comment] 2015-04-07 20:08
@sameersbn no i did not. as i said, the first fix solved the problem, there was no need to try the second.

**Comment by sameersbn** [comment] 2015-04-08 06:48
@smoebody ok.. can you revert the first fix and apply the second fix and let me know if it also resolves the issue?

**Comment by smoebody** [comment] 2015-04-08 16:23
@sameersbn ok, with the issue i get the following error:
````
2015/04/08 16:07:43 [alert] 2773#0: *15 readv() failed (13: Permission denied) while reading upstream, client: 172.17.0.116, server: gitlab.xxx.xxx, request: "GET /xxx/xxx.git/info/refs?service=git-upload-pack HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/xxx/xxxgit/info/refs?service=git-upload-pack", host: "gitlab.xxx.xxx"
````
as you can see, nginx prefixes the socket with an **http://** sometimes... thats when its not working.

both fixes mentioned above resolve the issue. for the second fix inserting the `proxy_buffering off` was enough.

**Closed** 2015-04-13 12:15 UTC
