### ISSUE TITLE
emoji in wiki not working

### ISSUE THREAD

**Issue by rishid** [sameersbn/docker-gitlab#196] opened 2014-11-06 16:16 UTC
I just started playing around with this image today and cannot seem to get emoji to work in the wiki. Is the image missing the emoji assets?
```
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa
OS/Arch (client): linux/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa
Containers: 3
Images: 49
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 55
Execution Driver: native-0.2
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.1 LTS
WARNING: No swap limit support

CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS              PORTS                                                   NAMES
7bb1a81dab63        sameersbn/redis:latest        "/start"               22 hours ago        Up 22 hours         6379/tcp                                                redis-gitlab        
d9c76069a15c        sameersbn/postgresql:latest   "/start"               22 hours ago        Up 22 hours         5432/tcp                                                postgresql-gitlab   
446495e9405c        sameersbn/gitlab:7.4.3        "/app/init app:start   22 hours ago        Up 15 hours         443/tcp, 0.0.0.0:10022->22/tcp, 0.0.0.0:10080->80/tcp   gitlab

```

**Comment by VPusher** [comment] 2015-01-16 17:08
:+1:  experiencing the same issue with "...gitlab/gitlab/assets..." buggy links. It seems the **GITLAB_RELATIVE_URL_ROOT** is repeated.

**Comment by sameersbn** [comment] 2015-01-19 04:22
@VPusher this issue is similar to #218, but the causes are different. This problem should probably be resolved in upstream gitlab. I haven't had the chance to install gitlab locally (i.e. not using docker) so I cannot be 100% sure.

**Comment by sameersbn** [comment] 2015-03-24 05:27
@VPusher @rishid Can you try with release `7.9.0`. Gitlab has switched its emoji library in this release. Lets check if that resolved this issue.

**Comment by cmckni3** [comment] 2015-09-02 23:11
Emoji on a wiki page works for me in 7.14.1. The preview of the emoji in the text area doesn't display correctly though. The url is using the wrong digest for some reason.

![2015-09-02_18-10-46](https://cloud.githubusercontent.com/assets/735717/9646943/f65eb9ca-519d-11e5-83ba-6dad8db5c7e2.png)

**Comment by cmckni3** [comment] 2015-09-02 23:31
There's something funky going on with either the [cache](https://github.com/gitlabhq/gitlabhq/blob/7-14-stable/app/controllers/projects_controller.rb#L201) or gemojione.

**Closed** 2015-09-03 04:52 UTC

**Comment by sameersbn** [comment] 2015-09-03 04:55
@cmckni3 thanks for looking into this. I found that the `cache:clear` rake task had to be executed during migration. Have added this, but it won't take effect until the next version change. You can manually execute the rake task to resolve the issue.

```bash
docker exec -it sudo -HEu git bundle exec rake cache:clear RAILS_ENV=production
```

**Comment by cmckni3** [comment] 2015-09-03 05:07
Ok, but clearing the cache didn't fix it for me

**Comment by sameersbn** [comment] 2015-09-03 05:12
@cmckni3 maybe you need to restart gitlab after.

**Comment by cmckni3** [comment] 2015-09-03 05:18
:+1: 

Fixed.

I ran `cache:clear` and restarted GitLab
