### ISSUE TITLE
Pages service does not start after upgrading from 13.12.4 to 14.0.0

### ISSUE THREAD

**Issue by Aoiujz** [sameersbn/docker-gitlab#2375] opened 2021-06-28 02:42 UTC
Pages service does not start after upgrading from 13.12.4 to 14.0.0，then upgraded to 14.0.1 and the same problem occurred.

```
time="2021-06-28T01:01:42Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:42Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:42Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:43Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:43Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:43Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:45Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:45Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:45Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:48Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:48Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:48Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:27Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:27Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:27Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:28Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:28Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:28Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:30Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:30Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:30Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:34Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:34Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:34Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
```time="2021-06-28T01:01:42Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:42Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:42Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:43Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:43Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:43Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:45Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:45Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:45Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:48Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:48Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:48Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:27Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:27Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:27Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:28Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:28Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:28Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:30Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:30Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:30Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:34Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:34Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:34Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"

**Comment by lukas-runge** [comment] 2021-06-29 09:51
Same issue for me:
![image](https://user-images.githubusercontent.com/21328241/123777037-1c07c300-d8d0-11eb-94d0-4f633a56f601.png)

I am having gitlab pages behind traefik so url is https but traffic behind traefik is http. Do I need to reconfigure something in `gitlab.rb` to have it working in 14.x.x? Till now this config worked fine for me:

```Ruby
pages_external_url "http://pages.service42.me"
gitlab_pages['inplace_chroot'] = true
gitlab_pages['access_control'] = true
```

Thanks already for helping out!
Kind regards,
@lukas-runge

**Comment by lukas-runge** [comment] 2021-06-29 09:52
Same issue for me:
![image](https://user-images.githubusercontent.com/21328241/123777037-1c07c300-d8d0-11eb-94d0-4f633a56f601.png)

I am having gitlab pages behind traefik so url is https but traffic behind traefik is http. Do I need to reconfigure something in `gitlab.rb` to have it working in 14.x.x? Till now this config worked fine for me:

```Ruby
pages_external_url "http://pages.<domain>.<tld>"
gitlab_pages['inplace_chroot'] = true
gitlab_pages['access_control'] = true
```

Thanks already for helping out!
Kind regards,
@lukas-runge

**Comment by Aoiujz** [comment] 2021-06-30 14:22
> Same issue for me:
> ![image](https://user-images.githubusercontent.com/21328241/123777037-1c07c300-d8d0-11eb-94d0-4f633a56f601.png)
> 
> I am having gitlab pages behind traefik so url is https but traffic behind traefik is http. Do I need to reconfigure something in `gitlab.rb` to have it working in 14.x.x? Till now this config worked fine for me:
> 
> ```ruby
> pages_external_url "http://pages.<domain>.<tld>"
> gitlab_pages['inplace_chroot'] = true
> gitlab_pages['access_control'] = true
> ```
> 
> Thanks already for helping out!
> Kind regards,
> @lukas-runge

Where is the `gitlab.rb`? Why can I only find the `gitlab.yml`

**Comment by kkimurak** [comment] 2021-07-01 04:45
@Aoiujz  
FYI, `sameersbn/gitlab` is source-installed gitlab image, so you can only find `gitlab.yml` for configuration purpose. (For strictly, `gitlab.rb` is exist e.g. `/home/git/gitlab/lib/gitlab.rb` and so on. But this is not a file you're looking for...)

`gitlab.rb` is used for omnibus-installed gitlab to make easier to update `gitlab.yml` via  commands (`gitlab-ctl reconfigure`, for example). See https://docs.gitlab.com/omnibus/settings/gitlab.yml.html

Sorry for not helpful about "Pages service".

**Comment by lukas-runge** [comment] 2021-07-01 13:23
Hey @Aoiujz,

for me just adding
```ruby
gitlab_pages['internal_gitlab_server'] = 'http://localhost:8080'
```
to the `gitlab.rb` config via the environment variable `GITLAB_OMNIBUS_CONFIG` provided by docker solved the actual issue which was accessing the api instead of `disk` of the gitlab instance.



<details>
<summary><b>full <code>docker-compose</code> config of running gitlab as docker service behind traefik</b></summary>

```yaml
version: "3.7"

services:
    gitlab:
        container_name: 'gitlab'
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: 'git.host.tld'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
              # Add any other gitlab.rb configuration here, each on its own line

              # Main Site
              external_url 'https://git.host.tld'
              nginx['listen_port'] = 80
              nginx['listen_https'] = false

              # SSH interaction with git
              gitlab_rails['gitlab_shell_ssh_port'] = 30022

              # GitLab Pages
              pages_external_url 'https://pages.host.tld/'
              pages_nginx['listen_port'] = 80
              pages_nginx['listen_https'] = false

              gitlab_pages['inplace_chroot'] = true
              gitlab_pages['access_control'] = true

              gitlab_pages['internal_gitlab_server'] = 'http://localhost:8080'

              # SMTP Settings
              gitlab_rails['gitlab_email_from'] = "noreply@host.tld"
              gitlab_rails['smtp_enable'] = true
              gitlab_rails['smtp_address'] = "mail.host.tld"
              gitlab_rails['smtp_port'] = 465
              gitlab_rails['smtp_user_name'] = "noreply@host.tld"
              gitlab_rails['smtp_password'] = "*********"
              gitlab_rails['smtp_domain'] = "mail.host.tld"
              gitlab_rails['smtp_authentication'] = "login"
              gitlab_rails['smtp_tls'] = true
              gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        ports:
        - '30022:22'
        volumes:
        - './config:/etc/gitlab:Z'
        - './logs:/var/log/gitlab:Z'
        - './data:/var/opt/gitlab:Z'
        - '/etc/localtime:/etc/localtime:ro'
        networks:
            - web
        labels:
            traefik.enable: "true"

            # GitLab
            traefik.http.services.gitlab.loadbalancer.server.port: "80"

            # git.host.tld
            traefik.http.routers.git-host-tld.rule: "HostRegexp(`git.host.tld`, `pages.host.tld`, `{subdomain:[a-z]+}.pages.host.tld`)"
            traefik.http.routers.git-host-tld.service: "gitlab"
            traefik.http.routers.git-host-tld.entrypoints: "https"
            traefik.http.routers.git-host-tld.tls.certresolver: "mydnsresolver"


networks:
    web:
        external: true
```

</details>

I finally found this information partly in the Docs, there is actually a migration guide you might also find helpful: https://docs.gitlab.com/ee/administration/pages/#migrate-gitlab-pages-to-140

Furthermore there is an official GitLab issue for feedback on the topic which actually also contains a lot of problems users faced when transitioning to 14.x.x and some great solutions such as the one that solved my issue in the end: https://gitlab.com/gitlab-org/gitlab/-/issues/331699

I hope you can get your deployment up in running. Best of luck! 🙌🚀🍀 

Kind regards,
@lukas-runge

**Comment by Aoiujz** [comment] 2021-07-06 08:11
Hi @lukas-runge,

Thank you for your help, I tried the method you provided and all the methods provided on https://gitlab.com/gitlab-org/gitlab/-/issues/331699, Unfortunately, my problem still exists.

Anyway, thank you for your patient help.

**Comment by omueller** [comment] 2021-07-09 09:04
Unfortunately same situation on our setup after an upgrade from 13.12.1 to 14.0.2, so for now juste "+1, me too" comment. Also tried a few things, but no success yet.   Nothing in the changelog of gitlab 14.0.4 or 14.0.5 seems to mention this issue either.

**Comment by tvtamas** [comment] 2021-07-16 18:23
As a workaround addig the `domain-config-source=disk` line to the `/etc/docker-gitlab/runtime/config/gitlab-pages/config` file inside the gitlab docker container and then restarting the container fixed the issue for me. Of course only temporary fix, recreating the container will revert to original file.

This setting is deprecated and will be removed https://gitlab.com/gitlab-org/gitlab-pages/-/issues/382

If I understand correctly from 14.0 this is needed (as @lukas-runge mentioned above):

```
domain-config-source=gitlab # preferred way, requires api-secret-key and internal-gitlab-server
```

**Comment by Aoiujz** [comment] 2021-07-17 15:18
> As a workaround addig the `domain-config-source=disk` line to the `/etc/docker-gitlab/runtime/config/gitlab-pages/config` file inside the gitlab docker container and then restarting the container fixed the issue for me. Of course only temporary fix, recreating the container will revert to original file.
> 
> This setting is deprecated and will be removed https://gitlab.com/gitlab-org/gitlab-pages/-/issues/382
> 
> If I understand correctly from 14.0 this is needed (as @lukas-runge mentioned above):
> 
> ```
> domain-config-source=gitlab # preferred way, requires api-secret-key and internal-gitlab-server
> ```

I tried this method and the problem remains.

**Comment by sue445** [comment] 2021-07-19 13:37
I fixed at #2388

**Comment by sue445** [comment] 2021-07-20 13:28
In my case, `api-secret-key` and `gitlab-server` (or `internal-gitlab-server` ) were required.  So I created patch in #2389.

**Comment by Aoiujz** [comment] 2021-07-26 09:46
@sue445   I updated to 14.1.0 and this issue does not seem to be fixed.

**Comment by icedream** [comment] 2021-07-26 10:07
The merge that was supposed to fix this was not included in 14.1.0 I think, however I also tried building an image straight off the `master` branch that now has the fix merged and I still couldn't get beyond a default Nginx 502 Bad Gateway error. I'm looking into it why that's still the case.

**Comment by icedream** [comment] 2021-07-26 10:21
`/home/git/gitlab/.gitlab_pages_secret` did get created, the log at `/home/git/gitlab/log/gitlab-pages.log` is as follows:

```
{"level":"info","msg":"GitLab Pages Daemon","revision":"f2d82a4","time":"2021-07-26T10:20:21+02:00","version":"1.41.0"}
{"level":"info","msg":"URL: https://gitlab.com/gitlab-org/gitlab-pages","time":"2021-07-26T10:20:21+02:00"}
{"error":"GitLab API URL or API secret has not been provided","level":"fatal","msg":"could not create domains config source","time":"2021-07-26T10:20:21+02:00"}
```

**Comment by icedream** [comment] 2021-07-26 10:32
I see that it is supposed to write a configuration file to `/home/git/gitlab/gitlab-pages-config` but I don't see how it gets loaded by the gitlab-pages daemon. Is that supposed to happen implicitly in some way, and is it supposed to keep the placeholders like that?

```
# cat /home/git/gitlab/gitlab-pages-config
auth-client-id={{GITLAB_PAGES_ACCESS_CLIENT_ID}}
auth-client-secret={{GITLAB_PAGES_ACCESS_CLIENT_SECRET}}
auth-redirect-uri={{GITLAB_PAGES_ACCESS_REDIRECT_URI}}
auth-secret={{GITLAB_PAGES_ACCESS_SECRET}}
gitlab-server={{GITLAB_PAGES_ACCESS_CONTROL_SERVER}}
artifacts-server={{GITLAB_PAGES_ARTIFACTS_SERVER_URL}}
internal-gitlab-server=http://localhost:8181
api-secret-key={{GITLAB_INSTALL_DIR}}/.gitlab_pages_secret
# cat /etc/supervisor/conf.d/gitlab-pages.conf
[program:gitlab-pages]
priority=20
directory=/home/git/gitlab
environment=HOME=/home/git
command=/usr/local/bin/gitlab-pages
  -pages-domain pages.seidemann-web.com
  -pages-root /home/git/data/shared/pages
  -listen-proxy :8090
user=git
autostart=true
autorestart=true
stdout_logfile=/home/git/gitlab/log/%(program_name)s.log
stderr_logfile=/home/git/gitlab/log/%(program_name)s.log
```

**Comment by icedream** [comment] 2021-07-26 10:32
I see that it is supposed to write a configuration file to `/home/git/gitlab/gitlab-pages-config` but I don't see how it gets loaded by the gitlab-pages daemon. Is that supposed to happen implicitly in some way, and is it supposed to keep the placeholders like that?

```
# cat /home/git/gitlab/gitlab-pages-config
auth-client-id={{GITLAB_PAGES_ACCESS_CLIENT_ID}}
auth-client-secret={{GITLAB_PAGES_ACCESS_CLIENT_SECRET}}
auth-redirect-uri={{GITLAB_PAGES_ACCESS_REDIRECT_URI}}
auth-secret={{GITLAB_PAGES_ACCESS_SECRET}}
gitlab-server={{GITLAB_PAGES_ACCESS_CONTROL_SERVER}}
artifacts-server={{GITLAB_PAGES_ARTIFACTS_SERVER_URL}}
internal-gitlab-server=http://localhost:8181
api-secret-key={{GITLAB_INSTALL_DIR}}/.gitlab_pages_secret
# cat /etc/supervisor/conf.d/gitlab-pages.conf
[program:gitlab-pages]
priority=20
directory=/home/git/gitlab
environment=HOME=/home/git
command=/usr/local/bin/gitlab-pages
  -pages-domain pages.<domain>
  -pages-root /home/git/data/shared/pages
  -listen-proxy :8090
user=git
autostart=true
autorestart=true
stdout_logfile=/home/git/gitlab/log/%(program_name)s.log
stderr_logfile=/home/git/gitlab/log/%(program_name)s.log
```

**Comment by icedream** [comment] 2021-07-26 10:37
Found it I think, it seems the config only gets loaded if `GITLAB_PAGES_ACCESS_CONTROL` is set to `true` as evident here:

https://github.com/sameersbn/docker-gitlab/blob/73dae28e31167ff16539f31959a7a7fe9cd439d5/assets/runtime/functions#L1785-L1807

**Comment by Aoiujz** [comment] 2021-07-29 01:56
> Found it I think, it seems the config only gets loaded if `GITLAB_PAGES_ACCESS_CONTROL` is set to `true` as evident here:
> 
> https://github.com/sameersbn/docker-gitlab/blob/73dae28e31167ff16539f31959a7a7fe9cd439d5/assets/runtime/functions#L1785-L1807

@sue445 Could you able to fix this issue?

**Comment by sue445** [comment] 2021-07-29 02:04
@Aoiujz I understand the problem, but I can't fix it right away.
I think we can start in a couple of weeks.

**Comment by icedream** [comment] 2021-07-29 10:33
Current workaround on top of the existing fix:

1.  Edit `/etc/supervisor/conf.d/gitlab-pages.conf` so it has these two added arguments:
    ```
      -internal-gitlab-server http://localhost:8181
      -api-secret-key /home/git/gitlab/.gitlab_pages_secret
    ````
2.  Reread this edited configuration with `supervisorctl reread`.
3.  Recreate process group for GitLab Pages with `supervisorctl remove gitlab-pages` and `supervisorctl add gitlab-pages`, at this point the service should be back up and running.

**Comment by icedream** [comment] 2021-07-29 10:36
I should also note that adding `-config /home/git/gitlab/gitlab-pages-config` instead as an argument did not work. This config file has to be edited first to remove the other arguments and then replace `{{GITLAB_INSTALL_DIR}}` with `/home/git/gitlab` and it still would not get loaded in by the GitLab Pages daemon properly for me.

**Comment by Aoiujz** [comment] 2021-08-02 05:59
> Current workaround on top of the existing fix, if you jump into the container with `docker exec`:
> 
> 1. Edit `/etc/supervisor/conf.d/gitlab-pages.conf` so it has these two added arguments:
>    ```
>      -internal-gitlab-server http://localhost:8181
>      -api-secret-key /home/git/gitlab/.gitlab_pages_secret
>    ```
> 2. Reread this edited configuration with `supervisorctl reread`.
> 3. Recreate process group for GitLab Pages with `supervisorctl remove gitlab-pages` and `supervisorctl add gitlab-pages`, at this point the service should be back up and running, you can double-check with `supervisorctl status gitlab-pages`.

Thank you very much! In this way, it can works fine.

**Comment by tvtamas** [comment] 2021-08-05 13:31
For us version `14.1.1` of the container fixed the issue. We do not need to edit the `/home/git/gitlab/gitlab-pages-config` anymore by hand.

**Comment by sue445** [comment] 2021-08-06 08:34
@Aoiujz 

> Could you able to fix this issue?

I created patch at https://github.com/sameersbn/docker-gitlab/pull/2400 !

**Comment by lichuan6** [comment] 2021-08-17 09:35
We have GitLab access control disabled, during upgrading from 13.12.0 to 14.0.0, we have GitLab 502 error and GitLab pages error:

```
time="2021-08-17T15:15:51+08:00" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-08-17T15:15:51+08:00" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-08-17T15:15:51+08:00" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
```

Is this MR https://github.com/sameersbn/docker-gitlab/pull/2400 solve the problem?

**Comment by lichuan6** [comment] 2021-08-30 05:06
I built a custom image with the code changes in this MR https://github.com/sameersbn/docker-gitlab/pull/2400, I can confirm it works when `GITLAB_PAGES_ACCESS_CONTROL` is disabled in our cases.

Would you please approve this MR if you have time? @sameersbn

**Comment by statnmap** [comment] 2021-09-21 07:51
Could you please share how to build the custom image so that we can try the MR too?
We currently had to shut down all our Pages because of this access bug.
Thank you.

**Comment by kkimurak** [comment] 2021-09-22 11:19
@statnmap

1. See [github's documentation to checkout pull request locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).  
  Following the documents, checkout the MR you want to test (for this case it is #2400).
2. build the image as described in [README.md](https://github.com/sameersbn/docker-gitlab#installation). Executing `make build` is also  a choice because this repository contains Makefile that wraps `docker build`. It takes a while (depends on your environment. it took around 30 minutes in my case)

best,

**Closed** 2021-12-09 21:24 UTC
