### ISSUE TITLE
[question] Tag 8.6.5 not found in repository docker.io/sameersbn/gitlab

### ISSUE THREAD

**Issue by xsinx** [sameersbn/docker-gitlab#663] opened 2016-04-12 02:38 UTC
Hi Sameersbn,
Thank you for your awesome work for this repo.
Just want to check if the we should update the tag in docker hub for the docker-compose?
(p.s. I modified the yml to "latest" to pass this error for now.)

```
$ sudo docker-compose up
dkr_redis_1 is up-to-date
dkr_postgresql_1 is up-to-date
Pulling gitlab (sameersbn/gitlab:8.6.5)...
Pulling repository docker.io/sameersbn/gitlab
ERROR: Tag 8.6.5 not found in repository docker.io/sameersbn/gitlab
```

**Comment by SolidNerd** [comment] 2016-04-12 06:59
See #662

**Comment by sameersbn** [comment] 2016-04-12 07:15
duplicate of #662

**Closed by sameersbn** 2016-04-12 07:15 UTC
