### ISSUE TITLE
Users statistics are empty

### ISSUE THREAD

**Issue by MatthiasHertel** [sameersbn/docker-gitlab#2148] opened 2020-05-18 19:44 UTC
users statistics is 0 , but i have 5 users ... why ?

url:
https://gitlab.example.com/admin/dashboard/stats

![image](https://user-images.githubusercontent.com/8426566/82253084-8d94e400-9950-11ea-989c-5b5ab7a88913.png)

![image](https://user-images.githubusercontent.com/8426566/82253163-b1f0c080-9950-11ea-9ba9-f998d3ba6691.png)

**Comment by solidnerd** [comment] 2020-05-19 03:49
I can confirm this.

**Comment by solidnerd** [comment] 2020-05-21 20:50
This issue is also posted in the upstream check this link: https://gitlab.com/gitlab-org/gitlab/-/issues/215492

Another Link
https://gitlab.com/gitlab-org/gitlab/-/issues/216461. 

It seems that it will be fixed with 13.0 . 

I'll gonna close this right here because it's nothing related to our project.

**Closed by solidnerd** 2020-05-21 20:50 UTC
Labels: bug

**Comment by cwildfoerster** [comment] 2020-05-25 10:44
Just upgraded to 13.0. Still empty, but maybe the job hasn't ran yet.

**Comment by cwildfoerster** [comment] 2020-05-25 12:24
Yes, this is working now, i forced the `users_create_statistics_worker` cron job under Monitoring > Background Jobs > Cron

**Comment by MatthiasHertel** [comment] 2020-05-25 12:51
@cwildfoerster 
how do u upgrade ?
https://github.com/sameersbn/docker-gitlab/releases

this repo is still on 12.10.6 :thinking: 

did u used the official gitlab-ce image ?

is it possible without break anything ?

**Comment by MatthiasHertel** [comment] 2020-05-25 12:57
@cwildfoerster 
under: https://gitlab.example.com/admin/background_jobs i cannot find a cron like users_create_statistics , but i still on version 12.10.6 ... but in version 13.0 is the cron , right ?

**Comment by cwildfoerster** [comment] 2020-05-25 13:14
@MatthiasHertel yes 13.0.0 see https://github.com/sameersbn/docker-gitlab/pull/2154 for more info. 13.0.0 tag is not on docker hub yet, use latest and make sure your postgresql database is correctly migrated to 11.

**Comment by solidnerd** [comment] 2020-05-25 16:52
@MatthiasHertel @cwildfoerster  The automatic release broke today in the morning. I restarted it and it will be available in ~ next 30 Minutes.

**Comment by cwildfoerster** [comment] 2020-05-25 17:01
Its all good, but maybe you/we should add another info to the postgresql upgrade readme part about if you have a pretty old installation from the 9.6 days, the upgrade to 11 will fail because postgresql doesn't upgrade the more recent 10 dataset automatically.

**Comment by MatthiasHertel** [comment] 2020-05-26 10:09
@cwildfoerster 

hi i guess i have the problem u drescribed above.

i am on pretty old postgres 9.6 and the image version is pinned on 9.6-2.

docker-compose.yml (snippet)
```
postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
gitlab:
    restart: always
    image: sameersbn/gitlab:latest
    depends_on:
    - redis
    - postgresql
```

do u know what i have to do to upgrade on gitlab 13 (latest)?
