### ISSUE TITLE
code: 500 Page  Whoops, something went wrong on our end.

### ISSUE THREAD

**Issue by yujianglei** [sameersbn/docker-gitlab#895] opened 2016-09-18 11:52 UTC
hello:
   today,I restore my repo  from  gitlab service to  docker  container, and i have a problem with mysql syntax (MySQL server version for the right syntax to use near 'keys CASCADE') when restore repo.  So  I delete  keys  tables mannal,Now  Restore success.

   Finally,  i access my  project that restored  from  gitlab service to  docker  container,But Appear 500 errors. Please see follow logs:

1.gitlab-workhorse.log
10.10.21.80:5080 @ - - [2016-09-18 19:41:30.449793764 +0800 CST] "GET /assets/fontawesome-webfont-c812ddc9e475d3e65d68a6b3b589ce598a2a5babb7afc55477d59215c4a38a40.woff?v=4.5.0 HTTP/1.1" 200 83588 "http://10.10.21.80:5080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7" 0.001194
2016/09/18 19:41:31 ErrorPage: serving predefined error page: 500

2.production.log
Started GET "/weizhang/smc-cms" for 127.0.0.1 at 2016-09-18 19:50:13 +0800
Processing by ProjectsController#show as HTML
  Parameters: {"namespace_id"=>"weizhang", "id"=>"smc-cms"}
Completed 500 Internal Server Error in 65ms (ActiveRecord: 1.9ms)

OpenSSL::Cipher::CipherError (bad decrypt):
  app/models/project.rb:383:in `import_url'
  app/models/project.rb:413:in `external_import?'
  app/models/project.rb:405:in `import?'
  app/models/project.rb:421:in `import_in_progress?'
  app/controllers/projects_controller.rb:93:in `show'
  lib/gitlab/middleware/go.rb:16:in `call'

others  logs  is not errors.

**Comment by solidnerd** [comment] 2016-09-18 18:13
Hey,
this seems to be a duplicate of #866. The problem could be here that your `GITLAB_SECRETS_DB_KEY_BASE` is different from the imported Project.

**Comment by yujianglei** [comment] 2016-09-19 01:52
@solidnerd    thank you!   

The problem is solved,the  reason is GITLAB_SECRETS_DB_KEY_BASE is different from the imported Project.  

The original  key is configured in config/secrets.yml  files.

**Closed** 2016-09-19 01:54 UTC
