### ISSUE TITLE
Tag 8.6.5 not found in repository 

### ISSUE THREAD

**Issue by taniadaniela** [sameersbn/docker-gitlab#664] opened 2016-04-12 23:53 UTC
Hi.. I need the 8.6.5 image but I when I try to download it I get this error:
docker pull sameersbn/gitlab:8.6.5
Pulling repository docker.io/sameersbn/gitlab
Tag 8.6.5 not found in repository docker.io/sameersbn/gitlab

can you upload it please?

**Comment by lenovouser** [comment] 2016-04-13 00:04
Duplicate of #662

**Closed** 2016-04-13 07:19 UTC
