### ISSUE TITLE
Permission denied when starting GitLab using docker-compose

### ISSUE THREAD

**Issue by arun-gupta** [sameersbn/docker-gitlab#410] opened 2015-08-28 05:35 UTC
Ported the `docker-compose` file as shown at:

https://github.com/javaee-samples/docker-java/blob/master/attendees/cicd/docker-compose2.yml

Starting using this file gives:

```
cicd> docker-compose -f docker-compose2.yml logs
Attaching to cicd_gitlab_1, cicd_redis_1, cicd_postgresql_1
gitlab_1     | ERROR: 
gitlab_1     |   Please configure the database connection.
gitlab_1     |   Refer http://git.io/wkYhyA for more information.
gitlab_1     |   Cannot continue without a database. Aborting...
postgresql_1 | Initializing database...
postgresql_1 | initdb: could not create directory "/var/lib/postgresql/9.4": Permission denied
redis_1      | Starting redis-server...
redis_1      |                 _._                                                  
redis_1      |            _.-``__ ''-._                                             
redis_1      |       _.-``    `.  `_.  ''-._           Redis 2.8.4 (00000000/0) 64 bit
redis_1      |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1      |  (    '      ,       .-`  | `,    )     Running in stand alone mode
redis_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1      |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1      |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |                                  
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |       `-._    `-.__.-'    _.-'                                       
redis_1      |           `-._        _.-'                                           
redis_1      |               `-.__.-'                                               
redis_1      | 
redis_1      | [1] 28 Aug 05:30:33.001 # Server started, Redis version 2.8.4
redis_1      | [1] 28 Aug 05:30:33.001 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | [1] 28 Aug 05:30:33.001 * The server is now ready to accept connections on port 6379
redis_1      | [1] 28 Aug 05:30:33.001 * The server is now ready to accept connections at /var/run/redis/redis.sock
```

What database configuration is required to get the image going?

**Comment by sameersbn** [comment] 2015-08-28 10:54
@arun-gupta what is your environment are you using boot2docker on osx. If yes, this is a known issue and there is no workaround that I am aware of. see 
- https://github.com/sameersbn/docker-postgresql/issues/34
- https://github.com/sameersbn/docker-postgresql/issues/22

**Comment by arun-gupta** [comment] 2015-08-28 12:57
Docker Toolbox 1.8.0 a1
Docker version 1.8.1, build d12ea79

Any workarounds?

**Comment by sameersbn** [comment] 2015-08-28 14:05
What is your host os? are you using boot2docker or something for your docker host?

**Comment by arun-gupta** [comment] 2015-08-28 14:52
OSX 10.10.5

Docker Toolbox comes with Docker Machine that uses boot2docker.

**Comment by sameersbn** [comment] 2015-08-28 15:42
well the workaround is not use shared folders for the postgresql data

**Comment by arun-gupta** [comment] 2015-08-28 15:50
Currently `docker-compose.yml` uses the following definition for postgres:

```
postgresql:
  image: sameersbn/postgresql:9.4-3
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /Users/arungupta/tmp/gitlab/postgresql:/var/lib/postgresql
```

How do you recommend that should change?

**Comment by sameersbn** [comment] 2015-08-28 17:26
I believe `/Users/arungupta` is a shared folder between your VM and Host OS. Instead of using `/Users/arungupta` use a location on the VM itself which is not mounted from your host , eg. `/srv/docker/gitlab/postgresql:/var/lib/postgresql`

**Comment by arun-gupta** [comment] 2015-08-28 17:55
Hosting postgresql files on the VM is fine. Still getting after changing:

```
postgresql_1 | Initializing database...
postgresql_1 | initdb: could not create directory "/var/lib/postgresql/9.4": Permission denied
```

**Comment by sameersbn** [comment] 2015-08-29 07:56
@arun-gupta you will need to login to the VM and check out what the issue is. Maybe selinux is enabled in the VM, but I am only guessing.

**Comment by steinert** [comment] 2015-08-30 17:48
I could solve the "permission denied" issue on my OSX 10.10.5 the way Sameer suggests: Connect the docker volumes to some directory which is _outside_ of the directory that is configured as the shared directory in the VirtuslBox image (which is "/Users" in my default setup).

**Comment by cmckni3** [comment] 2015-09-02 23:30
Sometimes it's an issue when the folder already exists on the host machine. The user inside of the docker container running the command is more than likely a different user and UID.

I like to follow the data container paradigm for containers.

In development, I run redis and mongodb containers but I have stopped containers labeled `redis-data` and `mongo-data` so the data persists between upgrading the `mongo` and `redis` containers.

**Comment by sameersbn** [comment] 2015-09-03 04:59
@cmckni3 the data directory is `chown`ed before performing any writes. However things like selinux can get in the way of this operation unless the security policies of the directory is updated, see the readme under persistence. In other cases a partially initialized data directory will cause issues in which case it is wise to delete the existing directory before retrying as @cmckni3 indicated.

**Comment by sameersbn** [comment] 2015-10-17 05:50
were you able to resolve this?

**Comment by johnosorio** [comment] 2015-10-27 19:24
I have created one directory in /docker-data and put my volumes to write in it, ej:

volumes:
        - /docker-data/dbdata:/var/lib/postgresql

It's working without permission issues.

Thanks!

**Comment by sameersbn** [comment] 2015-11-01 07:51
closing this issue. reopen if required

**Closed by sameersbn** 2015-11-01 07:51 UTC
