### ISSUE TITLE
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.

### ISSUE THREAD

**Issue by xiaoyawl** [sameersbn/docker-gitlab#1627] opened 2018-06-04 11:09 UTC
I run the latest yml.And I get the problem

here it's logs

```Configuring nginx::gitlab...
Setting up GitLab for firstrun. Please be patient, this could take a while...
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
Loading /etc/docker-gitlab/runtime/env-defaults
Initializing logdir...
Initializing datadir...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitaly...
Configuring gitlab::monitoring...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::unicorn...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::lfs...
Configuring gitlab::uploads...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::cron_jobs...
Configuring gitlab::backups...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Setting up GitLab for firstrun. Please be patient, this could take a while...
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.```

**Comment by Wyall** [comment] 2018-06-05 17:12
I got the same, after that message everything tries to restart and it happens again and again. Is your's a QNAP by any chance? Mine is and I have the feeling their docker implementation is weird in many regards. Not sure if that's the problem here though.

**Comment by qq339837609** [comment] 2018-06-06 04:49
I have the same question and can't start docker.

**Comment by HsuNick** [comment] 2018-06-07 05:58
version is 10.8.3-1?

**Comment by Wyall** [comment] 2018-06-07 19:52
I think I tried 10.8.2, I quickly tried 10.8.3-1 now, seemed to have worked for me. From what I saw a key was found, then a restart and then everything spawned correctly.

**Comment by jboxberger** [comment] 2018-06-10 00:58
Same Problem with 10.8.3-1 directrly after the Update. After a Container resatart it seems to work.

**Comment by ulrichSchreiner** [comment] 2018-06-12 04:38
same here, 10.8.3-1.

**Comment by KonstantinKuklin** [comment] 2018-06-13 15:39
same on 10.8.3-1, 10.8.2

**Comment by KonstantinKuklin** [comment] 2018-06-13 16:31
wasted 1 hour, but the problem not relevant for Missing Rails.application.secrets...
What's going on there: 
- docker trying to start /sbin/entrypoin.sh
- find command to execute - /usr/bin/supervisord -nc /etc/supervisor/supervisord.conf &
- go to hell with - kill -15 $SUPERVISOR_PID
- trying to restart

was added in f31c4d71e0e0f54341615a8a11f13a6ba69d75c9

**Comment by dimm0** [comment] 2018-06-13 17:38
My understanding is that supervisord is supposed to be starting 2 times - first for initial config, and second for running the services. So it's starting supervisord, then killing it and waiting for all processes to finish, and then starting again. Not sure why though..

**Comment by dimm0** [comment] 2018-06-21 19:08
Still not fixed in the last 10.8.4 release

**Comment by dimm0** [comment] 2018-06-21 19:24
Not for me. It keeps restarting with the same error

**Comment by Nepoxx** [comment] 2018-06-26 16:08
I had this issue and stayed on 10.8.1, I just updated to 11.0.1 and I no longer have this issue.

**Comment by dimm0** [comment] 2018-06-26 17:19
It did work indeed!

**Comment by okaufmann** [comment] 2018-06-26 19:48
can just confirm this: it works now

**Comment by jboxberger** [comment] 2018-06-26 19:49
Same here!

**Comment by kev-landry** [comment] 2018-08-06 19:05
I have the same problem on 11.1.4.

**Comment by cuongtv-0172** [comment] 2019-12-12 07:50
i have problem same when running 12.5.2.

**Closed** 2020-05-13 23:50 UTC
Labels: wontfix

**Comment by fengfuyun52** [comment] 2020-05-28 09:07
sorry,the issue accour to me.but i have not solve it.
Running raketask gitlab:backup:create RAILS_ENV=production SKIP=$(GITLAB_BACKUP_SKIP) --trace...
** Invoke gitlab:backup:create (first_time)
** Invoke gitlab_environment (first_time)
** Invoke environment (first_time)
** Execute environment
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
** Execute gitlab_environment
** Execute gitlab:backup:create
** Invoke gitlab:backup:db:create (first_time)
** Invoke gitlab_environment
** Execute gitlab:backup:db:create
2020-05-28 16:39:34 +0800 -- Dumping database ...
** Invoke gitlab:backup:repo:create (first_time)
** Invoke gitlab_environment
** Execute gitlab:backup:repo:create
rake aborted!

Caused by:
GRPC::Unavailable: 14:channel is in state TRANSIENT_FAILURE
