### ISSUE TITLE
sameersbn/redis loop restarting

### ISSUE THREAD

**Issue by justinushermawan** [sameersbn/docker-gitlab#1657] opened 2018-07-02 13:17 UTC
I got a problem with `sameersbn/redis` container, it keeps restarting whenever I restart the container, can't start normally. I've already removed all containers, including gitlab, postgresql, and redis but the problem still appears. Gitlab itself and postgres have no problem, only redis.

Anyone has an idea how does this problem come?

**Comment by thomaskr** [comment] 2018-07-18 09:16
The problem seems to be caused by a new version of redis that runs in protected mode.
Try to add `--protected-mode no` to the command line. For example:
```
services:
  redis:
    image: sameersbn/redis:latest
    command:
    - --loglevel warning --protected-mode no
```

**Comment by sameersbn** [comment] 2018-07-27 12:15
guys, sorry about this issue. this is precisely why we should avoid the use of `latest` tag. PR #1680 builds on top of #1667. Please refer to it until it has been accepted and merged

**Comment by QuickJack** [comment] 2018-08-07 07:35
I have talked about the redis versioning problem a long time ago at https://github.com/sameersbn/docker-gitlab/issues/809.

**Comment by QuickJack** [comment] 2018-09-05 07:40
Does this problem still occur when using `sameersbn/redis:4.0.9-1`? Is it safe to update the redis container of an existing 10.8.4 instance to `sameersbn/redis:4.0.9-1` before the upgrade to GitLab 11.0.4?

**Comment by lordvlad** [comment] 2018-09-05 15:03
did it yesterday, works flawlessly. just mind the `--protected-mode no` cli
setting.

**Comment by lordvlad** [comment] 2018-11-06 19:44
just confirming, works without the `--protected-mode no` flag

**Closed** 2018-11-29 10:14 UTC
