### ISSUE TITLE
12.10.6 broke for me

### ISSUE THREAD

**Issue by vitosans** [sameersbn/docker-gitlab#2149] opened 2020-05-19 20:26 UTC
Upgraded to 12.10.6 today, and for me it very broken. I have the #2147 issue like others, but unlike others, I am not able to clone or interact with git at all. When I try to add the missing port, I get the following error: 

`git clone git@gitlab.xxxx.com:10022/my_project/my_project.git
Cloning into 'my_project'...
bash: /opt/gitlab-7.13.5-0/apps/gitlab/gitlab-shell/bin/gitlab-shell: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

This is really odd as that gitlab-shell is from many releases ago, so I am not sure why it's pulling that up. I have checked the container and 

GITLAB_SHELL_INSTALL_DIR=/home/git/gitlab-shell is exported.

**Comment by vitosans** [comment] 2020-05-19 20:46
A little more progress. At one time this machine ran git before this project existed, and it still had a /home/git - I removed that directory and now gitlab-shell works but it's not using the authorized_keys it's prompting me for a password. I think pathing has gotten messed up somewhere in this release.

**Comment by solidnerd** [comment] 2020-05-19 21:08
@vitosans  Read my comment from https://github.com/sameersbn/docker-gitlab/issues/2147#issuecomment-630364938 . I think this comes from sync the upstream configs and a new `upload:` key was introduced in https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/gitlabhq/gitlab.yml#L1087 . During the sed command will catch the `upload:` key and delete all lines below the gitlab.yml . This is why the gitlab shell config is missing.

**Comment by solidnerd** [comment] 2020-05-19 21:09
I'll close this because it's a duplicate of #2147 .

**Comment by vitosans** [comment] 2020-05-19 21:10
@solidnerd - shifting gears and digging into that. Thanks for the point in the right direction. I will let you know if I find anything.

**Closed by solidnerd** 2020-05-19 21:09 UTC
