### ISSUE TITLE
Gitlab LDAP user Acess Denied : New Version  9.1.0-1 issue

### ISSUE THREAD

**Issue by MACE-Zer0** [sameersbn/docker-gitlab#1192] opened 2017-04-26 08:33 UTC
hello . thanks to @GJRTimmer  for your help .. but only 2 users with all the power in the Active directory can enter .. the other users when trying to login get acess denied 403 ... im trying to see if its some kind of group or permition ... 

Did this happend to anyone ... what kind of acess to a user needs to enter with ldap  ???

![image](https://cloud.githubusercontent.com/assets/9946471/25425302/6e3aaf2c-2a63-11e7-9d87-5a48f19d380f.png)

**Comment by MACE-Zer0** [comment] 2017-04-26 08:43
did a copy of my user that can enter ... and the copy cannot enter .. so its not a group in the AD .. must be somewhere else !!!

**Comment by MACE-Zer0** [comment] 2017-04-26 09:07
dont know if this has anything to do with .. but the users that can enter where created in the previous version 9.05

**Comment by GJRTimmer** [comment] 2017-04-26 09:15
Weird,

I shall try, so create a test suite for it, see if I can reproduce it

**Comment by MACE-Zer0** [comment] 2017-04-26 09:20
403 seems to be a acess to content denied .. is there anywhere that says who has permitions to acess gitlab ??

**Comment by GJRTimmer** [comment] 2017-04-26 09:26
403 is HTTP Status Code: "Forbidden" to my knowledge

**Comment by GJRTimmer** [comment] 2017-04-26 09:27
how did you copy the user, because you shouldn't need to copy anything when upgrading
I just upgraded to 9.1.0-1 by just updating my docker-compose and run the upgrade command I created

**Comment by MACE-Zer0** [comment] 2017-04-26 09:27
i dint copy anything .. just rename the version inside the script .. and started the scrypt .. and it upgraded without any problems ...

**Comment by GJRTimmer** [comment] 2017-04-26 09:28
yeah that sounds correct, but what do you mean by earlier comment about 'copy user'

**Comment by GJRTimmer** [comment] 2017-04-26 09:29
can you not login with root ?

**Comment by GJRTimmer** [comment] 2017-04-26 09:29
should always be possible to select the correct login 'TAB' on the login screen 'LOCAL' and than just login with root.

**Comment by MACE-Zer0** [comment] 2017-04-26 09:29
in the active directory .. i did a copy of my user inside AD to another with a diferente name so i could check if a AD user simular to mine could enter and it cant !!!

yes i can login with root and .. with 2 users from AD .. new users give that error

**Comment by GJRTimmer** [comment] 2017-04-26 09:30
ohh oke, so to recap: Current users in the AD are not the problem, newly created within the active directory cannot enter.

**Comment by MACE-Zer0** [comment] 2017-04-26 09:31
![untitled](https://cloud.githubusercontent.com/assets/9946471/25427748/69cfdda6-2a6b-11e7-9384-4c195da8e99f.jpg)

i have 3 users that entered ok when i had the 9.0.5. , then i upgraded .. and didnt try to login with other users until today

**Comment by MACE-Zer0** [comment] 2017-04-26 09:32
no no .. no more users in the ad cant enter ... just the ones that are in gitlab ... all the 200 users that try to login give  403

**Comment by MACE-Zer0** [comment] 2017-04-26 09:33
the 2 users of ad that i tried are FULL AD admins ... but when i do a ad copy of my users and create a full ad admin as well it doesnt enter .. so its not  a AD power .. must be a gitlab permition or problem

**Comment by GJRTimmer** [comment] 2017-04-26 09:33
My advice, is to login into the active directory and check the newly created users, maybe the have to simple problem, and after copy copy the user in the AD then some settings gets reset.

Most common is the user must change password on login, this will cause a AD Error code which in turn will fail the binding, on GitLab LDAP.

Basically, login with that user first on a Windows machine, and it will probably ask to change to password to continue the login. After that login in Gitlab

**Comment by GJRTimmer** [comment] 2017-04-26 09:34
oke, so, the users in question can succesfull login into Windows I presume ?

**Comment by MACE-Zer0** [comment] 2017-04-26 09:34
yes .. no problem ... just to login with gitlab

**Comment by MACE-Zer0** [comment] 2017-04-26 09:35
can i clean cache in gitlab ??

**Comment by GJRTimmer** [comment] 2017-04-26 09:35
you can clena the cache without problem, just bring then down first

**Comment by MACE-Zer0** [comment] 2017-04-26 09:37
what are the folders to clean i didnt write them down ???

**Comment by GJRTimmer** [comment] 2017-04-26 09:38
have you checked if there is maybe a gitlab rake task for this ?

**Comment by MACE-Zer0** [comment] 2017-04-26 09:39
sudo gitlab-rake cache:clear

i run this command inside the docker ??

**Comment by GJRTimmer** [comment] 2017-04-26 09:39
RAKE Task: 
```bash
gitlab app:rake cache:clear
```

see https://github.com/sameersbn/docker-gitlab#rake-tasks on how to run rake tasks

**Comment by GJRTimmer** [comment] 2017-04-26 09:40
yes on a running environment

**Comment by GJRTimmer** [comment] 2017-04-26 09:42
just finishing my test docker-compose file with LDAP

**Comment by MACE-Zer0** [comment] 2017-04-26 09:49
dont know if this is a new version problem .. or if its something wrong here .. because its the first time with the new version i try to login with a user from ad since upgrade

**Comment by MACE-Zer0** [comment] 2017-04-26 09:49
the thing is the 2 users that entered with 9.0.5.. work fine ..bue since they are ad admins .. i tought maybe a permition thing .. but a user with same permitions cannot enter

**Comment by GJRTimmer** [comment] 2017-04-26 09:50
I htink it is just somehting very simple like new users get defaults blocked until they have been granted clearance by an admin

**Comment by GJRTimmer** [comment] 2017-04-26 09:50
I think you might be right, that's maybe a gitlab persmission thing

**Comment by GJRTimmer** [comment] 2017-04-26 09:52
My test setup is booting hopefully I configured LDAP correctly on the first go :-) but as you well know I might need a few minutes to configure it to work :-)

**Comment by MACE-Zer0** [comment] 2017-04-26 09:53
can i run the image with the 9.0.5 . that i have here in another folder .. or because it ugpraded componentes it cant run ??

**Comment by GJRTimmer** [comment] 2017-04-26 09:58
you cannot use the same volume locations all that data has been upgraded.

I have to reboot my test setup, because I have LDAP with SSL/TLS.

**Comment by GJRTimmer** [comment] 2017-04-26 10:03
I will try to produce the entire issue by creating a test for 9.0.5 make sure my LDAP works and then upgrade to 9.1.0-1

**Comment by MACE-Zer0** [comment] 2017-04-26 10:06
i removed the volumes from the gitlab image test that has the 9.0.5 .. and will try also

**Comment by MACE-Zer0** [comment] 2017-04-26 10:08
yap .. .with 9.0.5 ... all the users form AD can enter without any problems .. just tested with 9.0.5 test image ... it was the image we created before upgrade

**Comment by GJRTimmer** [comment] 2017-04-26 10:09
still working on having LDAP work on 9.0.5 before I can continue, have to figure out my own ldap settings in combination woith gitlab

**Comment by MACE-Zer0** [comment] 2017-04-26 10:13
there is some problem with new version ... or something went wrong ... how can i revert the main instance to 9.0.5 ... i have to delete the volumes ... or can i run some command ... 9.0.5 works fine

**Comment by GJRTimmer** [comment] 2017-04-26 10:13
think I found something
what is the value of you LDAP_USER_FILTER key ?

**Comment by GJRTimmer** [comment] 2017-04-26 10:13
Just reading the LDAP GitLab documentation

**Comment by MACE-Zer0** [comment] 2017-04-26 10:13
i didnt set a filter yet !!!

**Comment by GJRTimmer** [comment] 2017-04-26 10:14
perfect

**Comment by MACE-Zer0** [comment] 2017-04-26 10:14
with version 9.0.5 it works fine

**Comment by GJRTimmer** [comment] 2017-04-26 10:15
I'm booting 9.0.5 and first get LDAP to work

**Comment by GJRTimmer** [comment] 2017-04-26 10:31
oke, road so far, I have 9.0.5 up and running, and LDAP working, login works correctly.

B.T.W.
Within the documentation for LDAP I found 3 additional config keys which are not yet support by this image. We need to add an issue to add then.
- group_base
- admin_group
- sync_ssh_keys

See: https://docs.gitlab.com/ce/administration/auth/ldap.html

BRB, Lunch

**Comment by GJRTimmer** [comment] 2017-04-26 10:32
@MACE-Zer0 do the users in your LDAP have all different email addresses, because just reading all the documentation ?

**Comment by MACE-Zer0** [comment] 2017-04-26 10:33
reverted everything to 9.0.5 deleted the folders of the volumes ... and changed docker-compose back to 9.0.5 on main image ... started up .. and its on 9.0.5 and working ...

**Comment by GJRTimmer** [comment] 2017-04-26 10:33
@MACE-Zer0 

there is a RAKE task to check and verify a user on commandline

See https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/administration/auth/ldap.md

**Comment by MACE-Zer0** [comment] 2017-04-26 10:34
yes everyone has a diferent email .... user.name@domain.com...

**Comment by GJRTimmer** [comment] 2017-04-26 10:35
running upgrade to 9.1.0-1 will take several minutes

**Comment by MACE-Zer0** [comment] 2017-04-26 10:42
quick question .. the files .env .. you moved them to arquive .. they are no longer needed ??? or if i need to change somthing in smtp settings i can changed in the smtp.env still ??

**Comment by GJRTimmer** [comment] 2017-04-26 10:50
no you can remove them, the env files are designed to separate configuration, I use them to keep everything ordend, you can start using it by reading the documentation of docker-compose and use the env_files import directive in docker-compose

**Comment by GJRTimmer** [comment] 2017-04-26 10:53
Issue reproduced, I get a 403 on a newly created user in LDAP (OpenLDAP) but issue seems to be the same.

**Comment by GJRTimmer** [comment] 2017-04-26 10:54
I will check the rake command to see if can get more information, have you tried the rake command yet ?

**Comment by MACE-Zer0** [comment] 2017-04-26 10:54
so .... for now .. just remain on 9.0.5... if you need ldap

**Comment by MACE-Zer0** [comment] 2017-04-26 11:00
no .. could not run it inside gitlab container gave an error .. maybe im doing something wrong ....

**Comment by MACE-Zer0** [comment] 2017-04-26 11:06
Issue reproduced, I get a 403 on a newly created user in LDAP (OpenLDAP) but issue seems to be the same.

the users i was trying were not created recently ... have been here for more than a year in AD ... so its not olny for recently created user

**Comment by GJRTimmer** [comment] 2017-04-26 11:14
you have to run as git user
from the directory ~/gitlab

**Comment by GJRTimmer** [comment] 2017-04-26 11:14
```bash
git@gitlab:~/gitlab$ bundle exec rake gitlab:ldap:check --trace
```

**Comment by GJRTimmer** [comment] 2017-04-26 11:15
can you run on 9.0.5 to see what the normal output should be

**Comment by MACE-Zer0** [comment] 2017-04-26 11:24
where can i post the output of the rake ??

**Comment by MACE-Zer0** [comment] 2017-04-26 11:27
Server: ldapmain                                                                                                       
LDAP authentication... Success                                                                                         
LDAP users with access to your GitLab server (only showing the first 100 results)  

Checking LDAP ... Finished

**Comment by MACE-Zer0** [comment] 2017-04-26 11:28
LDAP users with access to your GitLab server (only showing the first 100 results)                                      
        DN: CN=Exchange Install Domain Servers,CN=Microsoft Exchange System Objects,DC=xxx,DC=xxx                
sAMAccountName: $xxxxxxxxxxxxxxxxxxx

**Comment by MACE-Zer0** [comment] 2017-04-26 11:30
sAMAccountName: xxxxx-xxxx$                                                                                       
        DN: CN=Cláudia Martins,OU=xxxxx,OU=xxxxx,DC=xxxxx,DC=xxxx                                              
sAMAccountName: xxxx.xxxx                                                                                        
                                                                                                                       
Checking LDAP ... Finished

**Comment by MACE-Zer0** [comment] 2017-04-26 11:30
thats the normal output

**Comment by GJRTimmer** [comment] 2017-04-26 11:30
I'm currently booting a 9.0.5
But this probably means that LDAP is broken on 9.1.0-1 (the -1 is a version number of this repo)
I suggest you post a issue with gitlab to have it fix in the next release.

**Comment by GJRTimmer** [comment] 2017-04-26 11:30
https://gitlab.com/gitlab-org/gitlab-ce/issues

**Comment by GJRTimmer** [comment] 2017-04-26 11:31
This is the output from 9.1.0

Remember when submiting use the actual version number 9.1.0 NOT 9.1.0-1

```log
git@gitlab:~/gitlab$ bundle exec rake gitlab:ldap:check
rake aborted!
LoadError: cannot load such file -- haml_lint/rake_task
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/lib/tasks/haml-lint.rake:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:452:in `run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:453:in `load_tasks'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/home/git/gitlab/Rakefile:10:in `<top (required)>'
(See full trace by running task with --trace)
git@gitlab:~/gitlab$
```

**Comment by GJRTimmer** [comment] 2017-04-26 11:34
i cannot reproduce a correct ldap check

**Comment by GJRTimmer** [comment] 2017-04-26 11:34
doing something wrong not sure what yet

**Comment by GJRTimmer** [comment] 2017-04-26 11:36
I successfully completed the command on 9.0.5 I will check 9.1.0-1 one final time

**Comment by GJRTimmer** [comment] 2017-04-26 11:37
9.0.5

```basb
git@gitlab:~/gitlab$ bundle exec rake gitlab:ldap:check RAILS_ENV=production
Checking LDAP ...

Server: ldapmain
LDAP authentication... Success
LDAP users with access to your GitLab server (only showing the first 100 results)
        DN: uid=********,cn=users,dc=********,dc=nl       uid: ********
        DN: uid=********,cn=users,dc=********,dc=nl      uid: ********
        DN: uid=********,cn=users,dc=********,dc=nl   uid: ********
        DN: uid=********,cn=users,dc=********,dc=nl       uid: ********
        DN: uid=gitlab,cn=users,dc=******,dc=nl      uid: gitlab

Checking LDAP ... Finished

git@gitlab:~/gitlab$
```

**Comment by MACE-Zer0** [comment] 2017-04-26 11:38
can u give me of the new version to put in the issue ??

**Comment by GJRTimmer** [comment] 2017-04-26 11:39
see your admin section: 9.0.1, I will sent a screen shot when my test container is back online

**Comment by GJRTimmer** [comment] 2017-04-26 11:40
what was your logging output on 9.1.0-1 for ```bundle exec rake gitlab:ldap:check RAILS_ENV=production```

**Comment by GJRTimmer** [comment] 2017-04-26 11:40
maybe even with ```trace``` you have to submit all this logging with it when submitting an issue

**Comment by MACE-Zer0** [comment] 2017-04-26 11:41
i have to upgrade again .. because i deleted the volumes to revert to the old version

**Comment by GJRTimmer** [comment] 2017-04-26 11:42
![gitlab-9 1 0](https://cloud.githubusercontent.com/assets/6072255/25432800/31f719ce-2a86-11e7-9129-c85dbd2d4947.png)
I will get the logging for you

**Comment by GJRTimmer** [comment] 2017-04-26 11:44
weird same output

**Comment by GJRTimmer** [comment] 2017-04-26 11:44
whcih means you have to explain the error and show your 403 screenshot

**Comment by MACE-Zer0** [comment] 2017-04-26 11:45
so far i wrote this

Hello ... after upgrade to the 9.1.0-1 ... could not login with ldap .. or open ldap ... users in and active directory cannot login ... ![6e3aaf2c-2a63-11e7-9d87-5a48f19d380f](/uploads/bb0a68fcab8e0c1e611371f16945c4cf/6e3aaf2c-2a63-11e7-9d87-5a48f19d380f.png)

After doing a test with a new system with 9.0.5 it works fine ... only users that already had logged in , in previous versions can login ... users that never logged in they cannot login in 9.1.0-1 with ldap it gives and 403 error.


git@gitlab:~/gitlab$ bundle exec rake gitlab:ldap:check works fine in 9.0.5 ...  

9.0.5

git@gitlab:~/gitlab$ bundle exec rake gitlab:ldap:check RAILS_ENV=production
Checking LDAP ...

Server: ldapmain
LDAP authentication... Success
LDAP users with access to your GitLab server (only showing the first 100 results)
        DN: uid=********,cn=users,dc=********,dc=nl       uid: ********
        DN: uid=********,cn=users,dc=********,dc=nl      uid: ********
        DN: uid=********,cn=users,dc=********,dc=nl   uid: ********
        DN: uid=********,cn=users,dc=********,dc=nl       uid: ********
        DN: uid=gitlab,cn=users,dc=******,dc=nl      uid: gitlab

Checking LDAP ... Finished

**Comment by GJRTimmer** [comment] 2017-04-26 11:45
weird in my upgraded 9.0.1-1 I cannot even login with already registered users ?!?!?

**Comment by MACE-Zer0** [comment] 2017-04-26 11:46
in mine .. the already registered users .. it worked ...

**Comment by GJRTimmer** [comment] 2017-04-26 11:47
found it, reset the content, so thats the reason, for some reason gitlab 9.1.0 does not create users, I will have a look at the logs

**Comment by MACE-Zer0** [comment] 2017-04-26 11:47
it the output in 9.1.0-1 the same as in 9.0.5 ?

git@gitlab:~/gitlab$ bundle exec rake gitlab:ldap:check RAILS_ENV=production
Checking LDAP ...

Server: ldapmain
LDAP authentication... Success
LDAP users with access to your GitLab server (only showing the first 100 results)
        DN: uid=********,cn=users,dc=********,dc=nl       uid: ********
        DN: uid=********,cn=users,dc=********,dc=nl      uid: ********
        DN: uid=********,cn=users,dc=********,dc=nl   uid: ********
        DN: uid=********,cn=users,dc=********,dc=nl       uid: ********
        DN: uid=gitlab,cn=users,dc=******,dc=nl      uid: gitlab

Checking LDAP ... Finished
 ???

**Comment by MACE-Zer0** [comment] 2017-04-26 11:48
delete the volumes and create directly from new version ?? ... what about ppl that have a lot of work ther e??

**Comment by GJRTimmer** [comment] 2017-04-26 11:49
for my setup it is, no errors on checking

delete volumes ???????

**Comment by MACE-Zer0** [comment] 2017-04-26 11:50
you sair reset the content .. i tought the volumes

**Comment by GJRTimmer** [comment] 2017-04-26 11:52
ohh you mean on my side. just forget.

Got some logging for you.

```bash
Started GET "/users/sign_in" for 172.20.0.1 at 2017-04-26 12:51:24 +0100
Processing by SessionsController#new as HTML
Completed 200 OK in 160ms (Views: 30.3ms | ActiveRecord: 9.8ms)
Started POST "/users/auth/ldapmain/callback" for 172.20.0.1 at 2017-04-26 12:51:33 +0100
Processing by OmniauthCallbacksController#ldapmain as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"DawfKO56PXnegtm+zRRQcIhbmOsQaPfMvpw5Wa9SFg8hAmTEU4p7ULVyP/uAmmj8FfDIiEAY/LJjIkYU3NFFWQ==", "username"=>"gert-jant", "password"=>"[FILTERED]"}
Completed 403 Forbidden in 120ms (ActiveRecord: 6.8ms)
```

**Comment by MACE-Zer0** [comment] 2017-04-26 11:54
issue created thanks for the logs

https://gitlab.com/gitlab-org/gitlab-ce/issues/31449

**Comment by GJRTimmer** [comment] 2017-04-26 11:54
I will try and find out how to increase loglevel

**Comment by GJRTimmer** [comment] 2017-04-26 11:59
please change to version in the issue
the gitlab communicty does not known  about the custom veriso of this docker image

please change to 9.1.0

**Comment by GJRTimmer** [comment] 2017-04-26 12:01
add also please comment the code sections correctly in MarkDown

use three ` like ``` then append example bash
Start tag = ``` bash (without the space between otherwise you don't see it)
End tag = ```

**Comment by MACE-Zer0** [comment] 2017-04-26 12:04
ok already changed version

**Comment by GJRTimmer** [comment] 2017-04-26 12:05
issue should be "Gitlab does not create LDAP users anymore in 9.1.0"

**Comment by MACE-Zer0** [comment] 2017-04-26 12:06
done .. thanks

**Comment by GJRTimmer** [comment] 2017-04-26 12:06
please also fix the highlighting

Debug logging of production.log
```log
Started POST "/users/auth/ldapmain/callback" for 172.20.0.1 at 2017-04-26 13:02:57 +0100
Processing by OmniauthCallbacksController#ldapmain as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"w6h3WoZgfVeSJcmXC3NvsMVnzDnJH7qa2SEg5SWaC/TvBgy2O5A7fvnVL9JG/Vc8WMycWplvseQEn1+oVhlYog==", "username"=>"gert-jant", "password"=>"[FILTERED]"}
  ActiveRecord::SchemaMigration Load (1.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
  Identity Load (1.2ms)  SELECT  "identities".* FROM "identities" WHERE "identities"."provider" = $1 AND (LOWER("extern_uid") = LOWER('uid=gert-jant,cn=users,dc=timmertech,dc=nl'))  ORDER BY "identities"."id" ASC LIMIT 1  [["provider", "ldapmain"]]
  User Load (3.5ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1  ORDER BY "users"."id" DESC LIMIT 1  [["email", "gjr.timmer@gmail.com"]]
  Namespace Load (2.7ms)  SELECT  "namespaces".* FROM "namespaces" WHERE "namespaces"."deleted_at" IS NULL AND (lower(path) = 'gert-jant' OR lower(name) = 'gert-jant')  ORDER BY "namespaces"."id" DESC LIMIT 1
Completed 403 Forbidden in 177ms (ActiveRecord: 18.4ms)
```

**Comment by GJRTimmer** [comment] 2017-04-26 12:07
please wait with copy, I will have to redact some

**Comment by GJRTimmer** [comment] 2017-04-26 12:07
done

**Comment by GJRTimmer** [comment] 2017-04-26 12:10
you can close this issue because you have submited one with gitlab, the error is not part of this container.

**Comment by MACE-Zer0** [comment] 2017-04-26 12:11
Thanks for you help in identifyng

**Closed** 2017-04-26 12:11 UTC

**Comment by MACE-Zer0** [comment] 2017-04-26 12:14
... to enable workhorse like u have .. its something in the docker-compose as well ??

**Comment by MACE-Zer0** [comment] 2017-04-26 12:29
trying to add the gitlab registry .. but i get an error ..

ERROR: Validation failed in file '/volume1/docker/gitlab/etc/docker-compose.yml', reason(s):
services.gitlab-registry.ports contains an invalid type, it should be an array

  gitlab-registry:
    container_name: gitlab-registry
    hostname: registry
    restart: always
    image: registry:2.5.1
    ports:
      -3500:5000
    volumes:
      - /volume1/docker/gitlab/var/lib/gitlab/shared/registry:/resgistry
      - /volume1/docker/gitlab/etc/certs:/certs
    environment:
      - REGISTRY_LOG_LEVEL=info

**Comment by MACE-Zer0** [comment] 2017-04-26 12:38
got it working but gave a warning 


 [DONE]
WARNING: Some networks were defined but are not used by any service: default:
Creating network "gitlab_default" with the default driver
Creating gitlab-registry
Creating gitlab-redis
Creating gitlab-postgresql
Creating gitlab
