### ISSUE TITLE
nginx fails when adding docker registry (long hostname)

### ISSUE THREAD

**Issue by roflmao** [sameersbn/docker-gitlab#772] opened 2016-06-29 09:29 UTC
```
2016/06/29 09:09:16 [emerg] 3176#3176: could not build server_names_hash, you should increase server_names_hash_bucket_size: 32
```

The hostname seems to long so have to set server_names_hash_bucket_size in nginx.conf to 64.
Is this configurable by ENV?

**Comment by ziirish** [comment] 2016-06-29 13:58
duplicate of #750

**Comment by SolidNerd** [comment] 2016-06-29 16:16
Hey,
at the moment it isn't configurable via envvar. If you want an workaround edit in your GitLab container your nginx config file `/etc/nginx/nginx.conf` and change `# server_names_hash_bucket_size 64;` to `server_names_hash_bucket_size 64;` after that restart the container. I will write later an envvar for it.

**Comment by SolidNerd** [comment] 2016-07-10 07:18
So #786 is merged. It will resolves your problem if you set `NGINX_SERVER_NAMES_HASH_BUCKET_SIZE ` to `64`. If this solves not your problem. Please open a new issue. Thanks for reporting this issue.

**Closed by SolidNerd** 2016-07-10 07:18 UTC
