### ISSUE TITLE
Does anyone have any idea why gitlab team prefers postgresql over mysql?

### ISSUE THREAD

**Issue by virtuman** [sameersbn/docker-gitlab#983] opened 2016-11-26 08:17 UTC
I've been using gitlab for quite some time and have been using mysql all this time. Since long time ago gitlab started to indicate that they prefer and recommend postgresql as a better option for gitlab. Does anyone have any input on whether or not it makes any difference and if it's worth to switch from mysql to postgresql as a DB for gitlab?
It seems super mega easy to switch, especially through backups, but is there a point?
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/mysql_to_postgresql.md

**Comment by r2evans** [comment] 2016-11-27 22:15
Perhaps: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/database_mysql.md

The first paragraph:

> We do not recommend using MySQL due to various issues. For example, case (in)sensitivity and problems that suggested fixes have.

(Multiple links to `mysql.com`.)

Other than that, your question of *"why gitlab prefers ..."* can only be answered by GitLab themselves, not here. If you are asking about *"why would &lt;somebody&gt; prefer ..."*, there are several non-gitlab-centric comparisons of RDBMSs (e.g., [this recent one](https://www.libertycenterone.com/blog/oracle-vs-mysql-vs-sql-server-vs-postgresql-which-dbms-is-the-best-choice-for-you/)), as well as a (not-as-new) [discussion on Quora](https://www.quora.com/What-are-pros-and-cons-of-PostgreSQL-and-MySQL).

I've found that many of the historically-noted differences (e.g., speed, SQL compliance, scalability, replication) are dwindling, and most people will do just fine with either. (I'm not a DB guru, though I've done minor administration on both.)

**Comment by ggtools** [comment] 2016-11-28 14:04
As PostgreSQL seems to be the DB of choice for gitlab team I guess it makes some sense to use this database especially if you are using docker-compose.

**Comment by r2evans** [comment] 2016-12-11 01:43
@virtuman, I haven't found any more compelling evidence in support of or against the use of one over the other. Have you seen anything that either (a) keeps you on mysql, (b) keeps you from using postgresql, or (c) some other deterrent for the switchover?

If not, I suggest you can close the issue to help with the growing number of out-standing problems that the repo maintainers have to deal with.

**Comment by sameersbn** [comment] 2016-12-11 14:29
@virtuman like it has already been mentioned i see two reasons why gitlab folks recommend using postgresql:

1. Gitlab development team mainly uses postgresql during their development and testing
2. MySQL does not follow the SQL standard strictly and sometimes exhibits unexpected behaviors.

If you want the exact reasons you should reach out to the gitlab development team directly. Marking this issue resolved.

**Closed by sameersbn** 2016-12-11 14:29 UTC
