### ISSUE TITLE
Upload user logo not display

### ISSUE THREAD

**Issue by fye** [sameersbn/docker-gitlab#234] opened 2015-01-08 10:26 UTC
Upload user pictures, find pictures do not show through the links to see photos, localhost when found locally. I use the IP address visiting gitlab service, do you know where I went wrong?

![360 20150108174157](https://cloud.githubusercontent.com/assets/1445582/5661202/e0bc725a-9763-11e4-8d43-81e3b5e7c6ea.png)

**Comment by sameersbn** [comment] 2015-01-08 13:30
@fye please share docker run command.

**Comment by fye** [comment] 2015-01-09 02:18
This is my docker command:

docker run --name=gitlab -d \
-e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' \
-p 10022:22 -p 10080:80 \
-e 'GITLAB_RELATIVE_URL_ROOT=/avatar-gitlab' \
--link redis:redisio \
--link mysql:mysql \
-v /opt/gitlab/data:/home/git/data \
sameersbn/gitlab:7.6.2

**Comment by so0k** [comment] 2015-01-10 00:17
add -e GITLAB_HOST so gitlab no longer refers to itself as "localhost" - image upload works for me after adding this.

**Comment by sameersbn** [comment] 2015-01-10 03:50
@fye can you please try @so0k's solution

**Comment by sameersbn** [comment] 2015-01-11 07:35
@fye I can confirm that I can reproduce your issue and also confirm that @so0k's suggestion resolves it. I am closing the issue for now. If you still have issues, please reopen.

**Closed by sameersbn** 2015-01-11 07:35 UTC

**Comment by fye** [comment] 2015-01-11 12:36
@sameersbn @so0k Sorry for late reply, i will try tomorrow.

**Comment by fye** [comment] 2015-01-11 12:46
@sameersbn @so0k Sorry for late reply, i will try tomorrow.

**Comment by fye** [comment] 2015-01-12 08:16
@sameersbn @so0k . It works, Thanks!

**Comment by so0k** [comment] 2015-01-13 03:27
You're welcome :)
