### ISSUE TITLE
Set external_url

### ISSUE THREAD

**Issue by mlpilla** [sameersbn/docker-gitlab#1043] opened 2017-01-05 14:20 UTC
Hello,

I am really enjoying this container, but I am using HTTP/HTTPS forwarding behind another server in the same machine. Thus, I am using ports 10080 and 10443 for HTTP and HTTPS, but users are supposed to access those from 80 and 443.

My problem is that I need to set the external_url so URLs presented in Gitlab's pages are rewritten to avoid adding ports that are not used. As far as I can see, there isn't an environment variable to configure it when the container is started, so I have to edit gitlab.rb.

I would like an additional configuration variable to deal with it. 

Thanks,

Pilla

**Comment by reynold-lariza** [comment] 2017-01-09 00:18
from your LB or nginx/apache config you would need to apply port forwarding. 

Mine is configured in an LB, therefore all requests go thru 443 on on public domain, and routed internally thru 10443.

I would recommend disabling http (port 80) if you already have 443, for better security.

**Comment by pilla** [comment] 2017-01-09 10:30
Actually  I have forwarding working all right, the problem is that some elements of served pages have links such as https://myhostname:10080/alink instead of the desired https://myhostname/alink. That breaks those elements. Avatars are a good example.

The relative_url option should fix it.

**Comment by silenaker** [comment] 2017-01-13 10:03
I attempted some way to set  external_url but there was no effect,  you did not need to set external_url  and only to change GITLAB_HOST and GITLAB_PORT is enough, the two env variables determine the external_url

**Comment by pilla** [comment] 2017-01-13 10:14
@silenaker , you are correct! I was so focused on external_url from Gitlab's docs that I let that possibility aside... thanks, please somebody close this issue.

**Closed** 2017-01-16 20:02 UTC
