### ISSUE TITLE
8.17.0 fails to start due to nginx error

### ISSUE THREAD

**Issue by JacobHenner** [sameersbn/docker-gitlab#1127] opened 2017-03-18 13:24 UTC
`2017/03/18 13:20:57 [emerg] 3230#3230: duplicate listen options for [::]:80 in /etc/nginx/sites-enabled/gitlab-pages:6`

I do not have pages enabled.

**Comment by solidnerd** [comment] 2017-03-18 13:31
I need some more information about your configuration. On the first View I'm not able to reproduce this error.

**Comment by JacobHenner** [comment] 2017-03-18 13:35
```
GITLAB_SSH_PORT: 22
GITLAB_HOST: <host>
SMTP_USER: <email>
SMTP_PASS: <pass>
IMAP_PASS: <pass>
IMAP_USER: <email>
GITLAB_EMAIL_DISPLAY_NAME: <displayname>
GITLAB_HTTPS: "true"
OAUTH_GITHUB_API_KEY: <apikey>
GITLAB_HTTPS_HSTS_ENABLED: true
OAUTH_GITHUB_APP_SECRET: <secret>
OAUTH_BITBUCKET_API_KEY: <secret>
OAUTH_BITBUCKET_APP_SECRET: <secret>
OAUTH_TWITTER_API_KEY: <secret>
OAUTH_TWITTER_APP_SECRET: <secret>
GITLAB_SECRETS_DB_KEY_BASE: <secret>
SIDEKIQ_CONCURRENCY: 5
UNICORN_WORKERS: 1
GITLAB_SECRETS_OTP_KEY_BASE: <otp>
GITLAB_SECRETS_SECRET_KEY_BASE: <secret>
GITLAB_TRUSTED_PROXIES: 172.17.0.1
```

**Comment by solidnerd** [comment] 2017-03-18 13:57
I'm quite not sure but I made a change use the latest build when it's available and report please feedback to me.

**Comment by umputun** [comment] 2017-03-18 16:46
using the latest image from dockerhub, getting the same

**Comment by greyferret** [comment] 2017-03-18 17:09
Same problem in 8.17.0:
```
2017/03/18 19:53:01 [emerg] 3218#3218: duplicate listen options for [::]:80 in /etc/nginx/sites-enabled/gitlab-pages:6
```

Host information:
```
$ docker -v
Docker version 17.03.0-ce, build 60ccb22
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

In my case, fixed by deletion `ipv6only=on` from line 6 of `/etc/nginx/sites-enabled/gitlab-pages`

**Comment by solidnerd** [comment] 2017-03-18 18:12
Wait again for the new latest release and check it again please. Here is the commit that should solves the problems. https://github.com/sameersbn/docker-gitlab/pull/1129/commits/d49d4b2daefd780f6cefa2e44fbbbb2948a387a6

**Comment by umputun** [comment] 2017-03-18 18:50
worked just fine, thx. ` INFO success: nginx entered RUNNING state`

**Comment by solidnerd** [comment] 2017-03-19 00:29
I will close the issue. If it still exists please reopen it.

**Closed by solidnerd** 2017-03-19 00:29 UTC

**Comment by lionep** [comment] 2017-03-21 12:10
Same error here, with 8.17.4
```
[emerg] 3259#3259: duplicate listen options for [::]:80 in /etc/nginx/sites-enabled/gitlab-pages:11
```

**Comment by solidnerd** [comment] 2017-03-21 12:12
Did you enabled GitLab Pages ?

**Comment by lionep** [comment] 2017-03-21 12:13
Yes, with env : 
```
- GITLAB_PAGES_ENABLED=true
- GITLAB_PAGES_DOMAIN=pages.example.com
```

**Comment by phpb-com** [comment] 2017-03-21 12:16
ipv6only should be removed from listen directive in pages nginx config, it conflicts with previous definitions.
