### ISSUE TITLE
Upgrade to 9.3.4

### ISSUE THREAD

**Issue by Laul0** [sameersbn/docker-gitlab#1278] opened 2017-07-04 14:44 UTC
After to have upgrading GitLab to 9.3.4, I can't access anymore to :
- Content of "Your Groups" page (loading at infini) / Explorer Public groups works
- Content of "Your Projects" page
- Content of profile page
- Lost the link to top left of current project (ex : MyProjects/GitLab/Tests) (Opacity 0 in css because the status keep at initializing...)
- Readme and date of last commit don't appear (loading at infini)
- Cannot access to branch of project

**Comment by splattael** [comment] 2017-07-04 14:48
I *cannot* confirm this. I've tried every single point you mentioned on my installation (also 9.3.4) and it worked like a charm.

Do you see any errors in `/admin/logs` or via `docker logs -f gitlab`?

**Comment by jostyee** [comment] 2017-07-04 14:49
Me neither, can't reproduce any issue you mentioned.

**Comment by Laul0** [comment] 2017-07-04 14:55
In admin log (production) : Filter chain halted as :ensure_project_found! rendered or redirected
Everethings seems to be ok in docker logs -f gitlab (no error)
Link example : https://gitlab.lsonline.fr/SharePoint/javascript-customactions (readme never loaded)

Thx for your first answers

**Comment by splattael** [comment] 2017-07-04 14:58
@Laul0 For me, the README from https://gitlab.lsonline.fr/SharePoint/javascript-customactions loads just fine. Note: I am not logged in!

**Comment by Laul0** [comment] 2017-07-04 15:01
Is loading each time your refresh ? I have to refresh several times...
One more things, I can't Push or Pull ! (I'm using GitKraken)

**Comment by Laul0** [comment] 2017-07-04 15:16
I think I thought why.... My "cert" folder has disappeared... I'll try to restore it (I don't know why his folder was deleted)... I will keep you informed

**Comment by Laul0** [comment] 2017-07-04 21:02
I found the reason, but not yet the solution... When I had updated GitLab to latest version, I don't know why the certs folder was deleted.... I had restored this folder and restart the container... But know I meet an old issue when you specify a self-signed and the browser that return the error : Too many redirections.
Since I use GitLab, I had never meet this issue! This is the first time.... Do you have a solution about that ?

**Comment by f3l1x** [comment] 2017-07-12 06:51
I think we could close it. 9.3.5 is already tagged, right? :-)

**Comment by Laul0** [comment] 2017-07-13 18:32
I'll test it and keep you in touch. Thx for this information

**Comment by Laul0** [comment] 2017-07-18 07:48
I tested with the latest version (3.9.5) and I've still the same issue :
![image](https://user-images.githubusercontent.com/15279205/28306039-22f3c48c-6b9e-11e7-8721-9a62a39a86d0.png)

**Comment by QuickJack** [comment] 2017-07-19 07:17
Does this mean that the problem will occur when using MySQL only?

**Comment by Laul0** [comment] 2017-07-22 14:19
Hi, I tested this the latest version (9.3.9) and the problem persists...
More details on my environment : I use GitLab Docker behind jwilder/nginx-proxy. I always used the same command line to launch the GitLab container and it always works before the GitLab 9.3.5.

**Closed** 2017-07-29 13:18 UTC
