### ISSUE TITLE
Gitlab container exits (times out) after exactly one minute

### ISSUE THREAD

**Issue by kevinsullivan** [sameersbn/docker-gitlab#327] opened 2015-05-22 00:19 UTC
I'm running Ubuntu 14.04. My web set-up is nginx as an HTTPS terminator. It forwards https://mysite.com to Apache, and https://mysite.com/ci to localhost:9000. I have carefully read the set-up instructions. I have included and excluded GITLAB_HTTPS=true. I have included and excluded HOST, SHH_PORT, etc. In all cases I see the same behavior: Redis and Mysql appear to be running fine. GitLab appears not to have trouble linking to them. But no matter what I do, the GitLab container is timing out and exiting consistently after exactly sixty seconds. Here's a very stripped down set-up. Same problem here. Perhaps someone can see what I'm doing wrong or perhaps there's another problem. 

sudo docker run --name=redis_gitlab -d sameersbn/redis:latest
sudo docker run --name=mysql_gitlab -d -v /var/gitlab/mysql:/var/lib/mysql sameersbn/mysql:latest
sudo docker run -d \
    -v /var/gitlab/data:/home/git/data \
    -v /var/gitlab/mysql/:/var/lib/mysql \
    --link redis_gitlab:redisio \
    --link mysql_gitlab:mysql \
    -p 9000:80 -p 2222:22 sameersbn/gitlab:latest

**Comment by kevinsullivan** [comment] 2015-05-22 00:52
I should add that "docker logs <container-id>" shows no log messages at all. (Earlier, when I did have a small configuration problem, I did see log messages, so I'm pretty confident that if log messages were being produced, I'd be seeing them.) And I'm running Docker version 1.0.1, build 990021a.

**Comment by diresi** [comment] 2015-05-22 06:25
I've seen the same symptoms yesterday, there was a weird (and unreproducible) docker problem where container links were appearently messed up. From within my gitlab container, access to all linked containers failed (I tried connecting with socat), although they were working from other ones. I had to restart all the images to get around this (docker run).

I've seen the 1-minute-timeout as well, but there were logs indicating that the DB connection failed.

**Comment by kevinsullivan** [comment] 2015-05-22 11:54
I did initially have a slight misconfiguration that resulted in a failed DB
connection. That did show up in the logs and was easy to diagnose and
correct. Now that I've fixed it, though, I am stuck -- with a
non-functioning system and no logs to help.

On Fri, May 22, 2015 at 2:25 AM, Christoph Rissner <notifications@github.com

**Comment by sameersbn** [comment] 2015-05-23 06:27
> sudo docker run --name=redis_gitlab -d sameersbn/redis:latest
> sudo docker run --name=mysql_gitlab -d -v /var/gitlab/mysql:/var/lib/mysql sameersbn/mysql:latest

What about the database user and schema for gitlab? Does it already exist?

> sudo docker run -d \
> -v /var/gitlab/data:/home/git/data \
> -v /var/gitlab/mysql/:/var/lib/mysql \
> --link redis_gitlab:redisio \
> --link mysql_gitlab:mysql \
> -p 9000:80 -p 2222:22 sameersbn/gitlab:latest

The ` -v /var/gitlab/mysql/:/var/lib/mysql` volume mount is not required. It is a leftover line from the previous releases. However this cannot be the cause of your issue. 

What the issue here is the database connection parameters have not been specified, specifically `DB_USER`, `DB_PASS` and `DB_NAME`. I think you are expecting the gitlab container to automatically fetch this from the mysql container using the link. If so, this only works if these have been specified in the `mysql` container run command. Otherwise you need to specify them in the gitlab run command (provided that the mysql database and user already exists)

You can try 

```bash
sudo docker run --name=redis_gitlab -d sameersbn/redis:latest

sudo docker run --name=mysql_gitlab -d \
  --env='DB_NAME=gitlabhq_production' \
  --env='DB_USER=gitlab' --env='DB_PASS=password' \
  -v /var/gitlab/mysql:/var/lib/mysql \
  sameersbn/mysql:latest

sudo docker run -it --rm \
-v /var/gitlab/data:/home/git/data \
--link redis_gitlab:redisio \
--link mysql_gitlab:mysql \
-p 9000:80 -p 2222:22 sameersbn/gitlab:latest
```

Or better yet use the commands from the quick start guide and build upon them.

P.S. GitLab recommends using `postgresql` over `mysql`. I suggest you take this recommendation seriously because you will face issues with mysql, maybe not immediately but eventually the cracks will show up.

**Comment by sameersbn** [comment] 2015-07-12 11:33
@kevinsullivan was your issue resolved? If yes, please close this issue.

Looks like a DB connection error to me. It explains the 1 minutes timeout.

**Closed** 2015-12-11 08:48 UTC
