### ISSUE TITLE
Get 500 INTERNAL SERVER ERROR when entering Admin->Setting->Metrics and Profiling

### ISSUE THREAD

**Issue by Chindada** [sameersbn/docker-gitlab#2397] opened 2021-08-04 07:35 UTC
`https://xxxxxxxxx/admin/application_settings/metrics_and_profiling`
![image](https://user-images.githubusercontent.com/46039903/128140765-5b9fbbfc-93e3-40d1-93a6-92a38c123167.png)

**Comment by tDo** [comment] 2021-08-04 09:13
Duplicate of #2387

**Closed** 2022-01-29 11:25 UTC
