### ISSUE TITLE
gitlab-workhorse fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by peterwillcn** [sameersbn/docker-gitlab#770] opened 2016-06-28 03:46 UTC
Downloading Go 1.5.3...
2016-06-28 03:44:49 URL:https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz [80147269/80147269] -> "/etc/docker-gitlab/build/go1.5.3.linux-amd64.tar.gz" [1]
mkdir -p _build/src/gitlab.com/gitlab-org/gitlab-workhorse
tar -cf - --exclude _build --exclude .git . | (cd _build/src/gitlab.com/gitlab-org/gitlab-workhorse && tar -xf -)
touch _build
fatal: Not a git repository (or any of the parent directories): .git
go build -ldflags "-X main.Version=-20160628.034457" -o gitlab-workhorse gitlab.com/gitlab-org/gitlab-workhorse
fatal: Not a git repository (or any of the parent directories): .git
go build -ldflags "-X main.Version=-20160628.034508" -o gitlab-zip-cat gitlab.com/gitlab-org/gitlab-workhorse/cmd/gitlab-zip-cat
fatal: Not a git repository (or any of the parent directories): .git
go build -ldflags "-X main.Version=-20160628.034510" -o gitlab-zip-metadata gitlab.com/gitlab-org/gitlab-workhorse/cmd/gitlab-zip-metadata
mkdir -p /usr/local/bin/
install gitlab-workhorse gitlab-zip-cat gitlab-zip-metadata /usr/local/bin/
Cloning gitlab-ce v.8.9.1...

**Comment by SolidNerd** [comment] 2016-06-28 07:52
Hey,
It's a duplicate of #696 . This error comes from that we are checking tarballs out instead of git repositorys. In my point of view we could ignore this error messages.

**Closed** 2016-06-28 08:01 UTC

**Comment by solidnerd** [comment] 2017-04-22 22:38
It's fixed now with #1187 and will be available in `9.1.0-1` or `latest`.
